- source/vibe/core/core.d
Small change to allow lowerPrivileges to accept a user and group as a argument to the function to give the developer more control on how it should lower the privileges when the application is running as root. (eg allowing the developer to hard code the user/group, command line options, custom configuration, etc).
> Allow lowerPrivileges to accept user and group as an argument

- source/vibe/web/rest.d
While I was working on implementing `@queryParam` / `@bodyParam` parameters (following #908), I was blocked by the client-side code generator which hardcoded [some stuff](https://github.com/rejectedsoftware/vibe.d/tree/master/source/vibe/web/rest.d#L366).
In addition, the usage of `Json` was a bit annoying, and blocking for the evolution of this module (while not on my priority list, I'd like to make serialization customizable).
Downsides:
- Potentially breaks code, but none that #908 did not already broke. If someone extended the client implementation, parameter change, so CT error. However, I think that this use case is rare and that some might be doing to mimic newly added functionalities (e.g., modifying the headers).
- Moar template: Obviously, `genQuery` / `genBody` introduce some …
> REST enhancement #1.1: Refactoring for client side code generator

- source/vibe/http/server.d
- source/vibe/http/websockets.d
The ping interval is fixed at 60 seconds.
The best thing would probably be to set it in the server settings, thus also allowing to disable it entirely.
For this, the ```WebSocket``` must have access to ```HTTPServerSettings```; the best way would probably be to expose a const reference to ```HTTPServerRequest.m_settings```, which I'm going to do in the next commit of this pull request.
> Add automatic ping on websockets

- source/vibe/http/websockets.d
This allows establishing a websocket connection directly in an
HTTPServerRequestDelegate, which is useful if one needs to make some
checks on the request (and possibly send an http response with an error
code) before opening the websocket.
Signed-off-by: Luca Niccoli <l.niccoli@awtech.it>
> Add doHandleWebsocket function

- dub.json
- source/vibe/core/drivers/libasync.d
- source/vibe/utils/array.d
Here are a couple quick fixes for the libasync driver:
- The apache bench tool didn't work because the connection wasn't being closed correctly.
- The circular buffer has been moved to heap to avoid making the GC scan it, which speeds up the server by ~70%.
> Fix libasync apache bench and quick optimization

- source/vibe/core/concurrency.d
- source/vibe/core/core.d
- source/vibe/core/driver.d
- source/vibe/core/drivers/libevent2.d
- source/vibe/core/file.d
- source/vibe/core/net.d
- source/vibe/core/task.d
- source/vibe/crypto/passwordhash.d
- source/vibe/http/common.d
- source/vibe/inet/path.d
- source/vibe/internal/meta/traits.d
- source/vibe/internal/newconcurrency.d
- source/vibe/utils/hashmap.d
- source/vibe/utils/memory.d
This add a bit of nothrowness in utilities (probably more to come), re-enable an unittest, and disable the new std.concurrency support when building with master (because it is simply not implemented).
There is still a LOT of nothrow to put here, and I think it'll be better to start with a small diff.
Btw, the 2 overloads of opApply would never be called. Signature selection for `opApply` is not at clever sadly :(
> Get Vibe.d ready for 2.067

- source/vibe/core/task.d
I had this assert triggered a few times. It's not useful without a message.
> Added assert message to messageQueue

- examples/rest/source/app.d
- source/vibe/web/common.d
- source/vibe/web/rest.d
Okay, this had been stalling in my computer for a while now, time to push it.
Those are the complements of `@headerParam`. Since most of the work had been done in #926 , this is pretty straightforward.
> REST enhancement #1.2: Implementation of @queryParam & @bodyParam

- source/vibe/core/drivers/libasync.d
This allows the local address to be retrieved.
> Local address not set correctly - Fixes issue #961

- source/vibe/data/serialization.d
An explicit Policy parameter allows to customize serialization of types
without having to modify them, which is useful if the types are supplied
by a library or if different serializations are needed.
The PR is not ready yet, needing documentation and tests, but it's working, so I would like some feedback.
An usage example (that pushed me to write the code) is serializing objects synthesized by [dproto](https://github.com/msoucy/dproto), which can be done with such a policy:
```
template BufferPolicy(Buf) if (__traits(compiles, Buf.init == Buf.init.opGet))
{
auto toRepresentation(Buf b) {
return b.opGet;
}
Buf fromRepresentation(typeof(Buf.init.opGet) v){
Buf b;
b = v;
return b;
}
}
```
which transforms the serialized form from:
```
{"fieldname":{"opGet":"fieldvalue"}}
```
to
``` …
```
> Allow policy-based serialization

- source/vibe/utils/memory.d
This is one of a few fixes I made in my iteration of the memory module and could have caused leaks if kept in vibe. I think there's also other occurrences in containers where elements are not destroyed properly
> struct destructors are not being called

- source/vibe/http/server.d
- source/vibe/stream/openssl.d
- source/vibe/stream/ssl.d
Provide access to a client's certificate information, which makes client
cert based auth/cert SSO a lot more useful.
> Add access to SSL peer certificate

- source/vibe/stream/openssl.d
This occurs a lot when using client cetificates, and then connections
are dropped a couple of times before they are succesfully estbalished:
[0B573E01:0B613C01 2015.01.28 17:11:07.064 WRN] Handling of
connection failed: Failed to accept SSL tunnel: error:140D9115:SSL
routines:SSL_GET_PREV_SESSION:session id context uninitialized
(336433429)
Assigning the local hostname as a context ID fixes this error.
As per OpenSSL documentation:
https://www.openssl.org/docs/ssl/SSL_CTX_set_session_id_context.html
> Get rid of missing SSL context errors

- source/vibe/utils/memory.d
I've started writing a pool stack and considered this as problematic if object B's destructor relies on an object owned by object A.
> Assume array hold stack construction ordering

- .travis.yml
The libasync driver is not yet ready to be built on these compilers, and I don't intend to work it out until a little later.
This will allow the vibe.d repo to go green again soon
> Exclude unsupported builds from travis

- dub.json
- source/vibe/core/core.d
- source/vibe/core/drivers/libasync.d
- source/vibe/core/drivers/libevent2.d
- source/vibe/core/sync.d
- source/vibe/core/task.d
- source/vibe/db/redis/redis.d
- source/vibe/http/common.d
- source/vibe/http/log.d
- source/vibe/http/server.d
- source/vibe/http/websockets.d
- source/vibe/internal/meta/uda.d
- source/vibe/stream/openssl.d
- source/vibe/stream/taskpipe.d
- source/vibe/utils/memory.d
- source/vibe/web/web.d
- tests/redis/source/app.d
This also adds a fix for HashMap reallocation issue pointed out earlier.
> Fix compilation on DMD v2.067

- examples/auth_basic/dub.json
- examples/auth_basic/source/app.d
- examples/auth_basic/views/index.dl
- examples/auth_basic/views/internal.dl
This is (more or less) the example from the web site pimped with 2 templates.
The directory is named in a way that digest authentication can be easiely added as next directory (in sorted order).
> Add example for basic authentication.

- source/vibe/db/redis/sessionstore.d
redis doesn't let empty hash. so insert place holder to initial
session key-value.
> Fix RedisSessionStore.create()

- source/vibe/templ/diet.d
With Jade templates, you can define a default block content which is used if no content for a block is provided.
This is also possible with vibe.d - but an assertion prevents this.
IMHO the assertion is a cut'n'paste error. Removing it enables use of default block content.
> Enable default block content in Diet templates

- source/vibe/templ/diet.d
A block comment
body
//
Line 1
Line 2
should be rendered as
<body>
</body>
Currently, the block content is treated as normal template code.
This PR fixes the output behaviour.
> Fix output of block comments

- examples/auth_digest/dub.json
- examples/auth_digest/source/app.d
- examples/auth_digest/views/index.dt
- examples/auth_digest/views/internal.dt
- source/vibe/http/auth/digest_auth.d
This is a minimal implementation of RFC 2069.
Possible future enhancements:
- Add the client IP to the nonce
- Implement qpop
- Retrieve user passwords from .htaccess file
> Add HTTP digest authentication.

- source/vibe/templ/diet.d
This is the Jade way to emit conditional comments but works
with all plain text starting with <, too.
See http://jade-lang.com/reference/comments/.
> Implement plain text starting with < in Diet templates.

- source/vibe/templ/diet.d
Currently, the template checks only this pattern:
tag#id1#id2
but not the patterns
tag#id1(id='id2')
tag(id='id1',id='id2')
This PR adds a check to enforce setting of id only once.
> Allow only set of one id at tag in Diet template.

- source/vibe/web/rest.d
The template parameter is actually called `I`, not `T`.
> Fix name of interface type used in deprecation of "index" method

- source/vibe/web/rest.d
A common problem I was encountering with REST was how painful it was to test failing cases (as the module should warn on interfaces error), as well as the duplication of code to have error both in client and server.
This centralize the error checking in a single CTFE function that is called from 2 static asserts. If the function returns non-null, it means there is an error (and the return is the error message).
Hence, it makes it quite easy to test issues, such as #949 which I originally intended to fix when I started this branch.
Note that `static assert (ParamNames[i].length, ..)` could never be false, as `std.traits.ParameterIdentifierTuple` would not compile (unless this has to do with an older release?). I fixed the test.
EDIT: Actually, this static assert now works in 2.067.
> [REST] Reorganize error handling + fix issue #949

- source/vibe/templ/diet.d
The hidden comment from the web site
//-title there is no title
is actually processed as
<//-title>there is no title<///-title>
because there is no whitespace between - and t. Jade treats //-title
as a hidden comment.
This PR fixes the parsing problem. I moved all the comment handling
code into one place, too.
> Fix parsing of hidden comments

- source/vibe/http/server.d
The apple’s user agent Darwin/14.3.0 send the “Transfer-Encoding”
header value “Chunked” which make vibe.d request to fail
> Fixed chunked Bad Response for Darwin/14.3.0

- dub.json
This update adds memutils as a dependency. I intend to use it where libasync and its driver use HashMap, Array, FreeListRef and other manual memory operations. I've already started separating the vibe.d manual memory management from the libasync memory management with the last pull regarding DMD 2.67.0 compatibility fixes.
The new memory management is mostly based on your code, but it adds Phobos containers including red black tree and array, along with improvements in user experience for reference counting and object embedding (`alias this T` => `mixin Embed!T`). This will probably be used to implement the timers directly in libasync. It also implements scoped pools which are used to override the GC in tree-like structures such as [DOM, Json and XML …
> Update libasync dependency with memutils

- source/vibe/web/rest.d
This fixes a regression introduced by #1001. The following triggered an out of bounds error:
```
interface APIv1Countries {
import vibe.web.rest;
@path("/") @property Bson get();
}
```
> Added length check to re-enabled `@path("/")`

- source/vibe/core/core.d
- source/vibe/core/drivers/libasync.d
- source/vibe/core/log.d
- source/vibe/core/sync.d
The `assert(!m_queue)` assumes that the task wasn't initialized yet if the event loop isn't running. Now that the event loop can be turned on and off, this isn't true anymore.
The `yield()` was added in the test because the Task unlocking mechanism doesn't generate yielding in the libasync driver, nor does it trigger a kernel signal to pause the thread and process the locking queue after an unlock. This is voluntary behavior, the TaskMutex lock waiter queue will be processed at the next run of the event loop and any lock-holding tasks will resume at that time. Yielding at ManualEvent.emit() would (maybe) process those locks instantly (depending on the ordering of tasks to be resume) but may also create unnecessary performance issues.
Finally, the `getEventLoop().exit()` was in …
> Fix exitEventLoop and synchronization unittest issues in libasync

- .gitignore
- source/vibe/web/common.d
- source/vibe/web/rest.d
- source/vibe/web/web.d
This had been deprecated in fe6a5de7433140660b14af28e9540b22c198c1c7 and so this message is there since July 2013 (and not relevant anymore). Time to remove it ?
> Remove deprecation notice for index handling in vibe.web.rest

- examples/rest/source/app.d
- source/vibe/web/common.d
- source/vibe/web/rest.d
- Make @rootPathAttribute the default: it just scales better, there is rarely a point in having multiples interfaces at the root.
- Kill RootPathAttribute and use PathAttribute only instead: There was no real difference between @rootPath and @path, as they were mutually exclusive (path on method, rootPath on interface) and had the same behavior (e.g. they are always relative). This will obviously make user code less error-prone.
- Communicate the settings to the sub-interface.
> Simplify @path handling

- examples/websocket/public/index.html
I found mistype in examples/websocket/public/index.html
Original:
\</htnl\>
Fixed:
\</html\>
> fix mistype : examples/websocket/public/index.html

- source/vibe/utils/memory.d
Compare this corresponding fix in Phobos:
https://github.com/D-Programming-Language/phobos/pull/3143
> Remove cast that no longer works with DMD master

- source/vibe/templ/parsertools.d
- source/vibe/web/i18n.d
The bug prevented extraction of strings with escape sequence, e.g. "\n".
> vibe.web.i18n: Fix bug (Range violation) in wrapText

- source/vibe/http/common.d
Some webDav extensions use the REPORT method to get information about
the existing resources
> Added REPORT method for webDAV

- source/vibe/core/core.d
- source/vibe/core/drivers/libevent2_tcp.d
- source/vibe/core/task.d
Adding a missing `package` protection that erroneously wasn't checked before (https://github.com/D-Programming-Language/dmd/pull/4558).
Also, https://github.com/D-Programming-Language/phobos/pull/3172 introduced a regression in `indexOf` that requires explicit slicing to work around.
> More compatibility fixes for changes in DMD & Phobos

- source/vibe/internal/meta/traits.d
@Geod24 Just a quick verification, if there is anything subtle that would preclude non-ref args.
> Fix isOpApplyDg to accept non-ref args.

- source/vibe/http/client.d
Replaces rejectedsoftware/vibe.d#929 which I accidentally opened on my master branch.
Since the response does not have access to the request headers,
the expected protocol must be supplied as a parameter.
This is needed, for instance, to create client-side websockets.
> Add HTTPClientResponse.switchProtocol()

- source/vibe/http/auth/digest_auth.d
The current implementation of Digest authentication does not work in FireFox. He uses comma+space as a directives delimiter.
Plus added toLower () as in [RFC 2617] (https://tools.ietf.org/html/rfc2617) said:
> The realm directive (**case-insensitive**) is required for all authentication schemes that issue a challenge. The realm value (case-sensitive), in combination with the canonical...
> strip() DigestAuth directives and make them case-insensitive.

- source/vibe/core/log.d
Specifically, `Variant` erroneously had a `@trusted` destructor, which has been corrected here:
https://github.com/D-Programming-Language/phobos/pull/3227
(The affected functions are templates, and get their `@safe`-ty inferred anyway.)
> Make it possible to log unsafe objects

- source/vibe/core/drivers/libevent2.d
- source/vibe/utils/memory.d
> Extend synchronized/nothrow workaround to DMD 2.068

- source/vibe/inet/webform.d
This optimization takes advantage of Content-Length if provided and avoids many calls to read/write, which gives me a 20% performance improvement.
> Use Content-Length Header in Form Uploads

- source/vibe/http/router.d
The removal notice has been around for more than a year (24 april 2014). It's time to stick a deprecate attribute on this. Based on #1104 to be green.
> Deprecate HTTPRouter

- source/vibe/http/websockets.d
Not sure why the payload length is limited to 125 bytes. Regular messages can be longer, so it doesn't seem to be an issue with vibe code. I found no mention of such a limit for close frames in the RFC.
> Add optional reason message and code to WebSocket.close

- examples/json/source/app.d
- source/vibe/data/bson.d
- source/vibe/data/json.d
- tests/redis/source/app.d
Hello, Vibe.D!
I've written about my problem on forum: http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/25482/
I use vibe.d on small commercial product, and two days ago I got this trouble.
One REST server (api.shodan.io) sent me a JSON like `{..., serial: 17559991181826658461, ...}`
I read the official JSON standard: http://json.org/
Unfortunately, it doesn't define bounds for a number value, thus `99999999999999999999999999` is a correct JSON value.
However the most real systems uses 64-bit (as maximum) signed and unsigned integers for describe integral values.
Thus, supporting of ulong is very needed for users.
I've added a new `Type` value: `uint_`, which represents `ulong` values.
I prefer `int_` type instead of `uint_` when it possible.
If the integral value x …
> support ulong values for Json

- source/vibe/data/json.d
[835f545](https://github.com/rejectedsoftware/vibe.d/commit/835f545fc4e4d0577cf32a251625ff96624424d6#diff-86df8637c7aa11d44c494d012fd79d09L254) raises an [error](https://travis-ci.org/rejectedsoftware/vibe.d/jobs/65295311) with ldc. This PR fixes it.
> fix BigInt initialization

- .travis.yml
- README.md
- dub.json
I tried to include libasync, but: https://travis-ci.org/Geod24/vibe.d/jobs/66281101 (FYI @ibuclaw ).
Also, while searching if GDC 4.9.2 was supported, I stumbled accross https://github.com/travis-ci/apt-package-whitelist/ , so I took the opportunity to remove the old hack for libev.
> Add travis testing for GDC 4.9.2 (FE 2.066, yay)

- source/vibe/mail/smtp.d
Callback is missing for startTLS - just a one line change
> Add callback for SMTPConnectionType.startTLS to vibe.mail.smtp.sendEmail

- source/vibe/http/router.d
- source/vibe/web/common.d
- source/vibe/web/rest.d
The first steps taken are to assert on an empty / null path in the router.
I then considered a special handling for empty string as path, which would basically make it work like '/'.
But that would be quite an annoying change, but it could be potentially dangerous on update. So there's now an assert in `vibe.web.common.extractHTTPMethodAndName`.
In addition, I realized that the web interface was using it, so I made the error message clearer. The change involved is quite trivial.
Note about unrelated changes: I (finally) set up editor config on my emacs. Which means everytime I save a file I edited, it is normalized to be conformant to the settings in `.editorconfig`, which is why there is so much noise.
> [REST] Allow empty path to be treated as '/'

- source/vibe/http/log.d
When the requested URL is > ~2000 bytes the server crashes and the process hangs forever using 100% CPU on Linux. Easily exploitable by malicious users.
> Fix range violation when writing to access log

- source/vibe/internal/meta/codegen.d
Turns out it was way simpler than anticipated. I actually didn't expect this snippet of code to compile...
> [REST] Fix issue #1144 : Support variadic typesafe arguments

- source/vibe/http/router.d
Copy-paste error I guess.
On another subject: I was getting an infinite loop in the tree match on my fork using a set of routes I can't really show here. I'll try to investigate further I only had to disable it for now, but I think the deprecation of "classical" matching strategy should be avoided right now.
> Fix route registration

- source/vibe/core/drivers/win32.d
This allow stop event loop from non-D thread without calling dll_thread_attach().
> Exit event loop after WM_QUIT message

- source/vibe/web/rest.d
Since #1091 is killing `2.065`, I think we'll have to wait after 0.7.24 to merge it.
In the meantime, those 2 commits will catch some obvious errors so they won't harm.
> [REST] Forbid `ref` / `out` on query / body params

- source/vibe/web/rest.d
This:
```D
@path("/")
interface RootInterface {
Data get();
}
auto r = new GithubAPI(agent, "https://api.github.com");
```
Would produce the following (Note the 2 slashes):
`REST call: GET https://api.github.com// -> 404, {"documentation_url":"https://developer.github.com/v3","message":"Not Found"}`
The URL concatenation part was a little too sharp for it's own good, so I simplified it in 3 branches.
> [REST] Fix URL concatenation in the client to avoid double slashes

- source/vibe/core/drivers/libasync.d
When no data is to be written/read, createTrunc must still create the file to avoid further file operations to fail.
> Libasync FileStream must createTrunc earlier

- source/vibe/data/serialization.d
`deserializeImp` requires a `Policy` param, and it wasn't being passed. Seems like a simple oversight.
> Add missing Policy param when deserializing member with @asArray

- source/vibe/core/drivers/libasync.d
The peek function returned at most 1 byte due to a logical error. This also fixes an assertion failure when finalizing a read-only stream (not sure if it should fail)
> Fix peek in libasync

- source/vibe/data/json.d
When `parseJsonString` receives a string which consists of only whitespace characters, it tries to read the front of empty string at [line 1040 in original code](https://github.com/rejectedsoftware/vibe.d/blob/38784138ad8cc8f442bd0e76a1b740040ff33fe5/source/vibe/data/json.d#L1040).
Then it throws `AssertError` which is not an `Exception`.
So I fixed it by enforcing string to be not empty before taking front of it.
> enforce JSON string to contain non-whitespace characters

- source/vibe/data/serialization.d
Adds the ability to deserialize immutable data. See unittest.
> Immutable data deserialization support

- source/vibe/core/drivers/libasync.d
This fixes numerous issues related to timers that I had only started noticing while doing more tests on OS X.
> Libasync timers not processing on idle

- source/vibe/http/client.d
This is a fix for the client. Returning null prevents reading if the stream is empty during a stream operation
> http/2 : Avoid returning null streams at all costs

- source/vibe/http/internal/http2.d
We add another buffer to the chain just in case the window size limit is overrun by a few bytes, to avoid breaking the connection completely
> HTTP/2 : Allow some margin on window size

- source/vibe/http/internal/http2.d
The submitHeaders function half-closes the stream because the data provider is not being passed.
> HTTP/2 - Fix client uploads

- examples/rest/source/app.d
- source/vibe/internal/meta/funcattr.d
- source/vibe/web/rest.d
This patch solve one common issue: the inability to write to write to the headers from the server code.
I thought the best way to do it was to use the existing semantic, namely ref and out parameters.
This P.R. also includes some cleanups.
> [REST] Add ability to write to the headers

- source/vibe/inet/webform.d
> multipart request: always skip boundary, fix #1220

- source/vibe/core/drivers/libevent2.d
- source/vibe/utils/memory.d
Workaround for `'_d_monitorenter' is not nothrow` for DMD 2.069. See issue #1098.
> Extend synchronized/nothrow workaround to DMD 2.069

- source/vibe/inet/webform.d
The end of stream is not always `--\r\n` in forms, but the boundary is always followed by `--`
> Fix Multi-part Upload

- source/vibe/web/rest.d
- source/vibe/web/web.d
So that the functions become chainable just like get/post/any and such.
> registerRestInterface and registerWebInterface should return the router

- source/vibe/http/server.d
Starting with DMD 2.067.1, the new atomicLoad() and atomicStore() functions are used.
At the core they use cmpxchg16b instruction which needs proper aligned data.
The shared HTTPServerContext[] is not properly aligned and causes a segmentation fault
with the upcoming LDC 0.16.0.
This PR adds align(16) to align the variable.
> cmpxchg16b instruction needs 16byte aligned data.

- source/vibe/core/core.d
- travis-ci.sh
- was complaining about `a` being used before initialized
- also failed with 2.068.1 b/c of linkage error
> fix and test release build

- source/vibe/http/client.d
Occurs when connection is closed before the worker has time to start
> Fix access violation in client when connection

- source/vibe/http/server.d
at least os x's terminal supports clickable urls, so with this you can directly click.
> make logged url clickable in terminal by adding protocol

- source/vibe/core/drivers/libasync.d
This fixes an issue where filenames are created with the wrong encoding and then not found when the UTF-8 encoding applies.
> Fix UTF-8 filenames on Windows

- source/vibe/core/drivers/libasync.d
This fixes the immediate return issue in waitForData for 0 second timers, amonst other problems.
I think a negative duration might be better suited for immediate timers, since the 0 second already has defined behavior in some cases, mostly because libevent seems to never set a timer (infinite duration)
> Fix behavior of a 0 second timer, avoid processing them in a task

- source/vibe/stream/openssl.d
- source/vibe/stream/tls.d
What we had discussed in the forum thread. Hopefully it can still make 0.7.26
> Disable SSL3 for TLSVersion.any and upgrade enum with TLS 1.1 and TLS 1.2

- source/vibe/http/server.d
Not sure if this is the best place for this, but it's the most convenient at least :)
My use case is to disable some monitoring-only requests, which I don't want to pollute the access.log with. In my case, these are just some internal web-services.
> Allow per request disabling of write to access log

- source/vibe/internal/meta/codegen.d
- source/vibe/web/internal/rest/common.d
- source/vibe/web/rest.d
- tests/rest/dub.json
- tests/rest/source/app.d
Switches the REST client over to use `RestInterface!T`. When this is merged, I'd like to finally move all private client/server implementation parts from `vibe.web.rest` into separate modules.
This reverts the mixin template based generation of methods, because the string mixin based version got a lot shorter due to `RestInterface!T`. At the same time, the method body is now a regular template, making it *much* easier to grasp.
> Refactor REST client

- source/vibe/core/core.d
- source/vibe/core/drivers/libasync.d
- source/vibe/core/drivers/libev.d
This fix has revealed some issues in the libev and libasync back ends and needs to be postponed to the next release.
> [post-0.7.24] Fix runWorkerTaskH when called outside of a task.

- source/vibe/web/internal/rest/jsclient.d
This fixes the `on_result` code being inserted when it isn't required.
> Use ReturnType!FT in JS Client Generator instead of undefined RT

- source/vibe/core/drivers/libasync.d
This should avoid the resumeTask issue, and with timeout for an added bonus
> Libasync ManualEvent in FileStream - fixes #1225

- source/vibe/stream/openssl.d
They have been disabled on Debian, causing vibe.d to fail to compile.
SSLv3 only connections can still be achieved by passing the appropriate
SSL_OP_NO_* options to OpenSSL
See #1315
> Dont use OpenSSL SSLv3* methods

- source/vibe/http/router.d
- source/vibe/http/server.d
This allows for emitting the correct path when using a URLRouter with a prefix.
Consider the index of a router with prefix "/a/deep/path" which renders:
```jade
a(href="#{req.rootDir}") rootDir
a(href="#{req.routerRootDir}") routerRootDir
```
The following is output:
```html
<a href="../../../">rootDir</a>
<a href="../../../a/deep/path/">routerRootDir</a>
```
> Add HTTPServerRequest.routerRootDir property

- examples/rest-collections/dub.json
- examples/rest-collections/source/api.d
- examples/rest-collections/source/app.d
- source/vibe/web/internal/rest/common.d
- source/vibe/web/rest.d
- tests/restcollections/dub.json
- tests/restcollections/source/app.d
This PR adds syntactic support for item collections in REST interfaces. It does so in a backwards compatible manner w.r.t interface definition (i.e. existing interfaces stay the same except for defining an additional item key type/name).
Open issues:
- ~~`@path` annotations currently have to be used manually to get nice URLs (see test project)~~
- ... don't remember, but there was something else
~~The current `ItemID` `TypeTuple` is going to be replaced by a `struct` that at the same time defines the types and names of the key parameters. The interface generator will then validate all methods to have the right parameters and will automatically generate a proper method path (`":key/method"`).~~
This PR depends on #1266
> REST collections

- source/vibe/stream/zlib.d
This fixes an issue where zlib is not guaranteed to call deflateEnd or inflateEnd.
It also fixes an assertion failure that occurs when the underlying stream is closed prematurely.
> Zlib memory leak and leastsize assertion

- source/vibe/core/drivers/libevent2.d
Implements RAII-style freeing mechanism for manually allocated object, which fixes a bug that leaves objects hanging in the heap on connection failures.
fixes #1321
> Free TCPContext on connection failure - fixes #1321

- source/vibe/core/drivers/libasync.d
Read buffer is currently destroyed when the connection is closed, which prevents the reader from progressing. It has been moved to wait for finalize to be called.
fixes #1326
> (Libasync) Destroy the readBuffer on finalize - fixes #1326

- source/vibe/http/websockets.d
- source/vibe/inet/url.d
added ws/wss to the URL package
made changes to the Frame struct  and Websocket class to allow it to be
used as a server and client.
> added support for websocket clients

- source/vibe/core/drivers/libasync.d
Avoid a busy wait when running I/O outside fibers.
> Busy wait in Task.init I/O causes cpu spike

- source/vibe/http/common.d
for the implementation of a S3 Library we needed more granular control over the http chunks.
( see https://github.com/tamediadigital/vibe-aws/tree/feature-s3 )
this PR should not break any existing api but just adds the methods to manipulate the chunks headers.
> explicit chunk control

- source/vibe/inet/url.d
I tried running the unittests but somehow they all succeeded even though I deliberately broke one.
Still, the code seems to work with a simple test. I am secretly hoping for a CI that tests for me
> Support IPv6 Urls

- source/vibe/db/redis/redis.d
This made my latency go down from ~400ms to ~100ms in the browser when requests required multiple cache subrequests.
> Significant latency reduction in Redis

- source/vibe/core/drivers/libevent2.d
I found that not all DNS servers support the 'Bit 0x20' security mechanism (randomize query names to avoid hacking responses).
Libevent2 enables it by default(all other drivers do not enable it) and sometimes fail on resolveHost(), so it is better to disable it by default to avoid such problems.
> Disable 'Bit 0x20' mixed case option in dns resolve of libevent2 driver to make it working like other drivers

- source/vibe/core/drivers/timerqueue.d
Make sure the timers don't fail assertion if the GC destroys the queue before the timers are descheduled by a destructor on the GC.
> TimerQueue assertion failure in GC Destructors

- source/vibe/core/core.d
The current code uses C-style `sizeof` and `NULL`, and declares the wrong function name.
> Fix logicalProcessorCount for OSX

- source/vibe/core/drivers/libevent2_tcp.d
- source/vibe/stream/operations.d
- tests/tcp/source/app.d
This makes `Libevent2TCPConnection` use a `FixedRingBuffer` based read buffer instead of the one built into libevent, which is considerably slower (~18% slower when tested against a simple HTTP server). Currently, the libevent buffer still exists and removing it requires further work (using an `event*` instead of a `bufferevent*`).
> Libevent read buffer

- source/vibe/core/drivers/libev.d
- source/vibe/core/drivers/libevent2.d
- source/vibe/core/drivers/utils.d
- source/vibe/core/net.d
- source/vibe/http/server.d
libasync does not have setOption for AsyncTCPListener so I do think it is impossible to support TCPListenOptions.reusePort in libasync driver at present.
Therefore I only add it to libevent/libev drivers.
> add kernel-level distribution support(SO_REUSEPORT) for linux

- source/vibe/core/sync.d
BTW, why not to use `synchronized` instead of `performLocked`?
> make performLocked package(vibe)

- source/vibe/http/proxy.d
- source/vibe/http/server.d
- added accessors  to the raw streams in the http request and response
- added handling of CONNECT in the proxy request handler
- added handling of websockets upgrade in the proxy request handler
dub test passes
ran tests that websockets proxying works
ran tests that CONNECT proxying works
> Add websockets and CONNECT tunnel support to the HTTP proxy

- source/vibe/core/driver.d
- source/vibe/core/drivers/libasync.d
- source/vibe/core/drivers/libevent2.d
- source/vibe/core/drivers/win32.d
- source/vibe/core/net.d
- source/vibe/http/client.d
- tests/vibe.http.client.1389/dub.json
- tests/vibe.http.client.1389/source/app.d
This adds `HTTPClientSettings.networkInterface` and a `bind_address` parameter for `connectTCP`. See #1389.
> Allow specification of the local network interface for HTTP requests. Fixes #1389.

- source/vibe/db/redis/redis.d
- tests/redis/source/app.d
Ensures that the reference count is decremented if an exception happens when reading the reply header. Also closes the connection if an unexpected reply format is encountered.
Issue #1412.
> Ensure that RedisReply is properly cleaned up. Fixes #1412.

- source/vibe/core/core.d
- source/vibe/core/driver.d
- source/vibe/core/drivers/libevent2_tcp.d
- tests/vibe.core.net.1441/dub.sdl
- tests/vibe.core.net.1441/source/app.d
The previous fix for #1376 resulted in a possible task starvation when the peer reset the connection before the outbound buffer was drained. The new approach now always resumes the waiting task exactly once, no matter how many events happen and no matter in which order.
See #1441.
> Explictly avoid double-resumption of tasks during Libevent2TCPConnection.close(). Fixes #1441.

- source/vibe/data/serialization.d
The attributes `@ignore`, `@optional`, `@name`, `@byName` and `@asArray` now take a serialization policy as an optional template argument. With that specified, they only have an effect if `(de)serializeWithPolicy` is called with the same policy.
> Make all serialization attributes specifiable per policy. Fixes #1352.

- source/vibe/http/server.d
http://vibed.org/api/vibe.http.server/HTTPServerRequest.params
it has no documentation because the comment documents the import rather than the `params` variable
> Fixed documentation for HTTPServerRequest.params

- source/vibe/core/drivers/libevent2_tcp.d
- source/vibe/core/net.d
- tests/vibe.core.net.1452/dub.sdl
- tests/vibe.core.net.1452/source/app.d
Fixes the `InvalidMemoryOperationError` by avoiding the assertion and instead writing a warning message to the console. Fixes #1452.
> Issue1452 crash for tcp close at shutdown

- source/vibe/data/bson.d
> Bson opIndexAssign now uses "in" Bson argument

- source/vibe/http/client.d
- source/vibe/inet/url.d
- source/vibe/inet/urltransfer.d
- disconnect when changing host, schema, or port
- add defaultPort to URL to simplify code
> don't use TLS when being redirected from http to https

- source/vibe/http/server.d
(Second try, for curiosity of failed travis build.)
Adds to HTTPServerResponse a new property, `bool connected()`; which should return `true` in case remote peer still holding the connection and `false` ever since connection was severed, might be useful in some long-polling applications.
> Add HTTPServerResponse.connected property

- source/vibe/textfilter/markdown.d
I recently stumbled upon the Markdown parser and noticed that its output is not XHTML-compatible. This change should improve that, while staying compatible to HTML5 (although not to HTML4).
I adjusted the testcase too, but I didn't manage to actually run the tests (I'm not very used to D-land yet).
Please let me know what you think.
> Improve XHTML support by emitting XHTML/HTML5 compatible line break tags

- source/vibe/data/json.d
Json type used a pointer cast for conversions, which is illegal in CTFE.
Minimal case for reproduction:
```d
struct Charge
{
Json json = Json.emptyObject; // CTFE error.
}
```
Previously caused this error,
```
..\..\dub\packages\vibe-d-0.7.29-beta.1\source\vibe\data\json.d(108,104): Error: reinterpreting cast from inout(void*)* to inout(Json[string])* is not supported in CTFE
..\..\dub\packages\vibe-d-0.7.29-beta.1\source\vibe\data\json.d(115,87):        called from here: this.getDataAs()
..\..\dub\packages\vibe-d-0.7.29-beta.1\source\vibe\data\json.d(189,56):        called from here: this.m_object()
..\..\dub\packages\vibe-d-0.7.29-beta.1\source\vibe\data\json.d(153,51):        called from here: Json(null, cast(Type)0).this(cast(Json[string])null)
source\test\charge.d(16,22): …
```
> Fix Json pointer cast preventing use in CTFE.

- source/vibe/http/server.d
Honours the `X-Forwarded-Port` header, when present.
> #1490 Add support for X-Forwarded-Port header.

- source/vibe/http/server.d
It was impossible to set the status code of any RestInterface functions, even through `@after` because it always got overwritten by writeJsonBody which defaulted to 200
> Fixed writeJsonBody not to always overwrite statusCode to 200

- source/vibe/core/drivers/libevent2.d
There is no reason for them to be extern(C).
However, they can be easily corrupted / misinterpreted as
their name would be quite trivial in the resulting binary.
Related to rejectedsoftware/vibe.d#1475
> libevent2: Don't expose debug global data as extern(C)

- source/vibe/data/serialization.d
I can't get to work custom policy to deserialize enum values as I described in [forum](https://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/30890/#post-30898).
So I tried to find out why and found there is a bug in current implementation.
Problem is with the static if conditions order where even if the enum policy condition passed, it is not used as it is too far bottom and other condition gets prioritized before intended function.
With this PR it works ok.
Although as I looked on the other conditions, it seems to me, that they are wrong too, ie isCustomSerializable!T, isISOExtStringSerializable!T should probably also go upper. But I did not dig deeper.
Sample code, which works for me is this:
```D
import std.stdio;
import vibe.d;
enum Color {red, green, blue}
template …
```
> fix serialization conditions order

- source/vibe/http/client.d
- source/vibe/http/websockets.d
The RFC specify in section 4.1 (Opening Handshake, Client Requirements) that:
"The value of this header field MUST be a nonce consisting of a randomly
selected 16-byte value that has been base64-encoded"
However `randomUUID.toString` would return a 36 chars string.
As a result, the base64 encoding was 48 chars long instead of 24.
> Correct the client Websocket handshake

- source/vibe/textfilter/urlencode.d
- source/vibe/utils/string.d
When taking a string argument for validation, 'const(char)[]' should be used instead of 'string'.
That's because the former only promise the caller it won't modify the reference,
while the later ask for the strong promise (from the caller) that this argument shall never be modified.
In addition, some of those algorithm will either return a portion of the input string or a newly
allocated one.  This may result in a lot of otherwise avoidable allocations.  The runtime decision also
makes it impossible to use in `@nogc` code.
Ultimately, this code could be modified to take a buffer as parameter.
For the time being those functions were turned into templates.
Note: This is a rather shallow pass.
> Don't force immutability for string algorithms

- source/vibe/http/client.d
The original P.R. only fixed one of the overload.
> Fixup PR #1508: Do case-insensitive comparison of protocol upgrade

- source/vibe/core/drivers/win32.d
`Win32TCPConnection.tcpNoDelay` and `Win32TCPConnection.keepAlive` look implemented. But ends with line `assert (false)`.
In current state, [http_server](https://github.com/rejectedsoftware/vibe.d/tree/master/examples/http_server) example fails, when using `win32` configuration.
> assert(false) in implemented methods

- source/vibe/http/client.d
Fixes rejectedsoftware/vibe.d#1507
> Provide port information when the HTTP request isn't on the default port

- source/vibe/data/bson.d
- source/vibe/data/json.d
- source/vibe/db/mongo/collection.d
- source/vibe/db/mongo/connection.d
- source/vibe/http/dist.d
- source/vibe/web/common.d
This should not break existing code but allows us to define a version VibeDataNoOpDispatch. This prevents the compilation of the opDispatch functions in both Bson and Json.
We are semi-regularly running into issues with people using UFCS on a Json object. Instead of calling the function, it uses opDispatch and more often than not returns Json.undefined. This compiles without a problem and sometimes drives you mad when tests fail and you can't see the (not so) obvious issue.
Considering they are deprecated anyway, this allows a nice way for people to throw away this functionality immediately and make better use of things like UFCS.
> Added VibeDataNoOpDispatch version 

- source/vibe/data/json.d
`static assert("msg")` will never fail
> `assert(0, "msg")` instead of `assert("msg")`

- source/vibe/web/rest.d
The first commit strips trailing whitespace.
> Treat invalid JSON as bad request in the rest interface

- source/vibe/data/bson.d
- source/vibe/data/json.d
- source/vibe/data/serialization.d
This is a breaking change for any serializer implementations. The expectation though is that the only existing seriailzer implementations are currently the ones in vibe.d itself.
The traits struct in particular carries UDA information, which allows serializers to support serializer specific UDAs. The code has also been refactored a bit to reduce line length/visual noise.
> Let serializers get a type traits struct instead of the raw type.

- source/vibe/appmain.d
I don't know how, but I ended up with both of these defined and it caused a headache, perhaps this will help others see the problem quickly
> disallow defining VibeCustomMain and VibeDefaultMain together

- source/vibe/data/json.d
should add some more tests, but I believe this is a necessary change. Either this or throw an exception on serialising a nan. `undefined` is not a valid json literal and should never appear in any JSON output.
> nan -> null not undefined

- source/vibe/core/sync.d
When the semaphore reached the lock limit, tasks can compete for a lock but the waiter sometimes ended up having its lock snatched. This fixes the issue by freeing the lock only if no waiter was called.
> ConnectionPool's LocalTaskSemaphore Intermittent Infinite Wait Bug

- source/vibe/web/internal/rest/jsclient.d
- source/vibe/web/rest.d
fix #1565
some problem from #1564 fix also
> fix some rest js client problems

- source/vibe/utils/array.d
There is a problem when removing from the start index
> Fix FixedRingBuffer.removeAt

- source/vibe/utils/validation.d
Proposed fix for [issue 1580](https://github.com/rejectedsoftware/vibe.d/issues/1580).
> Fix validateEmail/isEmail inconsistency

- meson.build
Hello!
I am going to use Vibe.d in a project which is build using Meson, and also would like to make Vibe.d available in Debian/Ubuntu at some point.
Especially for the latter, we need some more sophisticated build system than Dub currently is. We need to install built software system-wide, generate proper pkgconfig files, allow to inject custom compile flags for the respective D compiler instead of using upstream's settings and most importantly using dependencies that are part of the system exclusively instead of downloading them from the web.
Dub can't do that (bugs filed with nothing happening), but Meson can do that and more.
Other options for this task would have been Automake or CMake, but Meson is much easier to use for this purpose (compiling D code) than the other two. You can …
> Add build configuration for Meson

- source/vibe/data/serialization.d
The documentation for `isStringSerializable` / `isPolicySerializable` is generated from the unittests.
The unittests are however in the wrong order, so that the docu for `isStringSerializable` is found where 
one would expect to see `isPolicySerializable` and vice versa.
See an example of the wrong docu at (see example code there):
http://vibed.org/api/vibe.data.serialization/isStringSerializable
http://vibed.org/api/vibe.data.serialization/isPolicySerializable
> seralizer: Fix wrong order of unittest/docu

- source/vibe/stream/botan.d
Compiler: ldc-1.0.0
vibe-d 0.7.30-rc.1 and botan 1.12.7
```
#349621 0x0000000000691b6d in vibe.stream.botan.CustomTLSPolicy.allowedEccCurves() const ()
#349622 0x0000000000691b6d in vibe.stream.botan.CustomTLSPolicy.allowedEccCurves() const ()
#349623 0x0000000000691b6d in vibe.stream.botan.CustomTLSPolicy.allowedEccCurves() const ()
#349624 0x0000000000691b6d in vibe.stream.botan.CustomTLSPolicy.allowedEccCurves() const ()
#349625 0x000000000071948a in botan.tls.messages.ClientHello.this(botan.tls.handshake_io.HandshakeIO, ref botan.tls.handshake_hash.HandshakeHash, botan.tls.version_.TLSProtocolVersion, const(botan.tls.policy.TLSPolicy), botan.rng.rng.RandomNumberGenerator, memutils.vector.Vector!(ubyte, memutils.utils.ThreadMem).Vector, memutils.vector.Vector!(immutable(char)[], …
```
> Infinite recursion in vibe.stream.botan.CustomTLSPolicy.allowedEccCurves w/ ldc

- dub.sdl
Compiling vibe.d projects fails with undefined references to zlib with gdc (Debian 6.2.0-10) 6.2.0 20161027
> Pass -lz when compiling with GDC

- .travis.yml
- core/vibe/core/concurrency.d
- core/vibe/core/connectionpool.d
- core/vibe/core/drivers/libevent2.d
- core/vibe/core/drivers/libevent2_tcp.d
- core/vibe/core/stream.d
- core/vibe/core/sync.d
- core/vibe/internal/allocator.d
- core/vibe/internal/freelistref.d
- data/vibe/data/bson.d
- http/vibe/http/client.d
- http/vibe/http/common.d
- http/vibe/http/server.d
- inet/vibe/inet/message.d
- redis/vibe/db/redis/redis.d
- stream/vibe/stream/memory.d
- stream/vibe/stream/multicast.d
- stream/vibe/stream/openssl.d
- stream/vibe/stream/operations.d
- stream/vibe/stream/tls.d
- stream/vibe/stream/zlib.d
- utils/vibe/internal/utilallocator.d
- utils/vibe/utils/array.d
- utils/vibe/utils/hashmap.d
- utils/vibe/utils/memory.d
- utils/vibe/utils/string.d
This deprecates the included allocator/memory module in favor of the one contained in Phobos.
> Switch to std.experimental.allocator.

- http/vibe/http/fileserver.d
Mostly based on https://github.com/rejectedsoftware/vibe.d/issues/716#issuecomment-220606604
Changes to that comment: added `-[X]` format and sending partialContent status code. Also some cleaner code and checks against bad requests.
Not sure how to add an automatic test but I did manually test it locally using this very simple file server in chrome and firefox:
```d
import vibe.http.server;
import vibe.http.fileserver;
shared static this()
{
auto settings = new HTTPServerSettings;
settings.port = 10716;
listenHTTP(settings, serveStaticFiles("data"));
}
```
My aim was only fixing media streams (audio & video + seeking), but pausing downloads and resuming also works now.
> fix #716 (Add partial content with range)

- http/vibe/http/fileserver.d
Ensuring Range contains exactly one `-` and also rethrow conv exceptions as badRequest (for example `Range j-8`)
> Safety checks in fileserver

- mongodb/vibe/db/mongo/connection.d
- mongodb/vibe/db/mongo/sasl.d
- mongodb/vibe/db/mongo/settings.d
The default is still MONGO-CR, even for server versions 3.0+ to maintain backwards compatibility. It can be switched by adding "authMechanism=SCRAM-SHA-1" to the connection query string.
> Implemented SCRAM-SHA1 authentication method for mongo

- core/vibe/core/core.d
- core/vibe/core/driver.d
- core/vibe/core/drivers/libasync.d
- core/vibe/core/drivers/libevent2.d
- core/vibe/core/drivers/win32.d
Both non-persistent and edge-triggered modes work perfectly for my libpq (PostgreSQL) wrapper.
> Non-persistent and edge-triggered modes for FileDescriptorEvent.

- http/vibe/http/fileserver.d
Currently when using **sendFile**, the *Content-Type* header is automatically set based on file extension. While this default behaviour is fine, the problem is that the header is overwritten if already explicitly set.
In my case, files are not stored using any extension, so all files are treated as *application/octet-stream*. I have the correct media type stored elsewhere, and it would be nice if I could manually specify this, without having the header overwritten internally.
> Respect explicitly set Content-Type in sendFile

- web/vibe/web/internal/rest/jsclient.d
Allow using the on_error function also when the XHR request fails completely (e.g. when the host is not available).
This is useful when needing feedback on whether or not the XHR request was successful or not.
If there's anything I can improve, please let me know!
> Propagate XHR error to on_error in JS RestInterface

- web/vibe/web/internal/rest/jsclient.d
Sorry again for previous mishap (https://github.com/rejectedsoftware/vibe.d/pull/1645).
This one also allows to always receive an error when the server responds with an error (in case could not update, etc...).
This time it's tested..
> Fix and further error handling capability

- data/vibe/data/json.d
- data/vibe/data/serialization.d
It fixes #1660.
I also added a unittest for serializing/deserializing AA whose key type is string-based enum.
I leave the case of AA with `@byName` because AA does not support this attribute yet (in implementation).
> Support deserialization of AA whose key type is string-based enum

- http/vibe/http/session.d
- redis/vibe/db/redis/sessionstore.d
Adds the capability to remove a field from a session.
It's named `remove` after the D's [HashMap `remove`](https://dlang.org/spec/hash-map.html#removing_keys)
> vibe.http.session: Allow to remove a field from a session

- source/vibe/db/redis/types.d
RedisHash!T did not compile when type T used a custom string serialization.
> Added a missing toRedis() -conversion for RedisHash.setIfNotExist

- examples/web-auth/dub.json
- examples/web-auth/public/styles/common.css
- examples/web-auth/source/app.d
- examples/web-auth/views/admin.dt
- examples/web-auth/views/home.dt
- examples/web-auth/views/layout.dt
- examples/web-auth/views/login.dt
- examples/web-auth/views/premium.dt
- examples/web-auth/views/settings.dt
- web/vibe/web/web.d
Vibe.d's authorization framework is amazing, but it's a quite hard to find examples for it (except for [its documentation](http://vibed.org/api/vibe.web.auth/)).
This is based on the original web service example, but instead of `@before` it uses the `vibe.web.auth` framework for access and role management. I added two dummy pages, s.t. the access roles can be checked.
I deliberately avoided using `SessionVar` as this would somewhat make the injection of the current `authUser` redundant in this example.
> Add web authentication example

- http/vibe/http/websockets.d
This PR adds support for retrieving a websocket connections close code and reason. Fairly straightforward, but vibe.d's source is all new territory so please advise if something is glaringly wrong or horrible.
The TL;DR implementation;
1. If we receive a close frame with at least enough bytes for a `short`, we read the short in as the close code
2. If the close frame contains more than enough bytes for a `short`, we read the short in as the close code and read the remaining bytes in as a character array for the close reason.
> Add support for retrieving the websocket close code/reason

- http/vibe/http/auth/basic_auth.d
Separates the authorization test from authorization enforcement.
Fixes #1449.
> Add checkBasicAuth function.

- data/vibe/data/json.d
It takes address of local variable `line` but it cannot be used outside this scope.
> Mark vibe.data.json.parseJsonString as trusted

- mongodb/vibe/db/mongo/connection.d
This is a fix for https://github.com/rejectedsoftware/vibe.d/issues/1715.
The change is to use the same cast as at: https://github.com/rejectedsoftware/vibe.d/blob/master/mongodb/vibe/db/mongo/connection.d#L370
> Fix for #1715

- source/vibe/http/server.d
- tests/vibe.http.server.1721/dub.sdl
- tests/vibe.http.server.1721/source/app.d
For variable body lengths, the server erroneously used chunked transfer encoding on HTTP/1.0 connections. Since there are still proxy servers that don't support HTTP/1.1, this can still be a practical issue. This instead switched to "Connection: close" without a "Content-Length" header.
Fixes #1721.
> Use "Connection: close" instead of chunked encoding on HTTP/1.0

- examples/rest/source/app.d
- tests/rest/source/app.d
- web/vibe/web/common.d
- web/vibe/web/internal/rest/common.d
- web/vibe/web/internal/rest/jsclient.d
- web/vibe/web/rest.d
This replaces #1676 and implements the suggested changes + fixes remaining errors.
> Implement whole-body parameters for the REST interface generator

- web/vibe/web/rest.d
Just a simple fix to REST handler when bool query parameter is used. Not all clients generates expected "true" so it should be case insensitive.
Also sending 0 or 1 is pretty common.
> Simple fix to REST bool query parameters

- core/vibe/core/drivers/libasync.d
- core/vibe/core/drivers/libevent2_tcp.d
- tests/vibe.core.net.1726/dub.sdl
- tests/vibe.core.net.1726/source/app.d
Fixes #1726 and possibly #1724.
> Fix TCP close behavior in case of cuncurrent read+write operations

- http/vibe/http/client.d
Corrected (copy paste) typos in ddoc comments for the write.*body methods for HTTPClientRequest.
> Corrected documentation for HTTPClientRequest

- .travis.yml
- meson.build
- travis-ci.sh
This PR fixes the meson builds and adds a few quirk fixes as well. It also allows testing Meson in Travis (LDC only for now).
The following issues exist and have been partially resolved:
* Meson doesn't allow absolute paths in `include_directories` anymore if they point to the source dir. This breaks a previous hack added to download 3rd-party dependencies. I added another hack to work around this for now, but I will raise this at Meson upstream now to get this resolved somehow.
* Building Vibe with DMD+Meson apparently doesn't work since DMD doesn't recognize the versioned library parameter. I am not sure of this is a Meson or DMD issue, at time I think it's Meson not translating a flag to the DMD-specific syntax. Will need some investigation.
The other change is installing the whole …
> Fix & test Meson builds

- stream/dub.sdl
Starting up new project from dub, mac OS X El Capitan V10.11.6 produces the following error
```
Failed to load package in /Users/tpuric/.dub/packages/vibe-d-0.8.0-beta.5/: /Users/tpuric/.dub/packages/vibe-d-0.8.0-beta.5/stream/dub.sdl(30:10): Error: Expected '=' after attribute name, not Value
Full error: dub.internal.sdlang.exception.SDLangParseException@source/dub/internal/sdlang/exception.d(16): /Users/tpuric/.dub/packages/vibe-d-0.8.0-beta.5/stream/dub.sdl(30:10): Error: Expected '=' after attribute name, not Value
----------------
5   dub                                 0x000000010de96076 void dub.internal.sdlang.parser.PullParser.error(immutable(char)[]) + 94
6   dub                                 0x000000010de96bf2 void dub.internal.sdlang.parser.PullParser.parseAttribute() + 362 …
```
> Fix SDLangParseException in mac

- .travis.yml
- meson.build
- travis-ci.sh
Older Meson versions had a bug which prevented library builds when DMD was used, which is why DMD+Meson builds were excluded in Vibe.d so far.
I resolved the issue in Meson, so we can now test with DMD as well, yay!
(I also updated the library versions for the current in development version)
> Allow building with Meson and DMD

- utils/vibe/utils/dictionarylist.d
The recently added `HTTPServerRequest.context` is a `DictionaryList!Variant`. That turns out quite cumbersome to work with. This pull request adds templated overloads for `DictionaryList`'s methods `get`, `opIndexAssign` and `addField` to get things to work intuitively.
> Improved usablity of DictionaryList with dynamic types

- utils/vibe/internal/meta/funcattr.d
- utils/vibe/internal/meta/traits.d
- web/vibe/web/internal/rest/common.d
- web/vibe/web/rest.d
> Handle "before" annotations on REST interface classes.

- core/vibe/core/drivers/libevent2.d
- utils/vibe/utils/array.d
@DBankov: This should hopefully fix the deadlock situation. Tested on my laptop and I get a scale factor of around 1,6x (performance still worse than it used to be). I can also observe the growing memory consumption.
> Fix GC related deadlock in the libevent driver

- http/vibe/http/server.d
- utils/vibe/internal/memory_legacy.d
- utils/vibe/internal/utilallocator.d
This works around a memory leak issue in `std.experimental.allocator.building_blocks.allocator_list.AllocatorList` ([17393](https://issues.dlang.org/show_bug.cgi?id=17393)). There is still a very high amount of virtual memory use, but reserved memory appears to be back to normal.
> Use a custom multi-region allocator for the HTTP server.

- stream/vibe/stream/operations.d
> Fix readUntilSmall/readLine for cases where the peek and the read paths are mixed

- data/vibe/data/json.d
> Output null instead of undefined with Json.undefined serialization

- inet/vibe/inet/webform.d
Content-Disposition fields can be passed as an unquoted string in which case the current parser fails.
https://tools.ietf.org/html/rfc6266#section-4.1
So I adjusted the parser to depend on semicolon as a separator or to use the rest of the input if the semicolon is not found.
For example .Net can send requests like this:
```
POST https://192.168.0.78:8082/api/v1/foos HTTP/1.1
User-Agent: bar
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Content-Type: multipart/form-data; boundary="7518e894-589d-44be-9a04-9f45c6124429"
Host: 192.168.0.78:8082
Content-Length: 55839
Expect: 100-continue
Connection: Keep-Alive
--7518e894-589d-44be-9a04-9f45c6124429
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=name
Some test
--7518e894-589d-44be-9a04-9f45c6124429 …
```
> Fix parseMultipartForm to accept unquoted strings

- data/vibe/data/bson.d
- data/vibe/data/json.d
- utils/vibe/utils/dictionarylist.d
Bson, Json and DictionaryList now return a named tuple with .key and .value members instead of plain tuples. Fixes #1763.
> Let byKeyValue return named tuples

- stream/vibe/stream/botan.d
Fixes
```
../vibe.d/stream/vibe/stream/tls.d(102,11): Error: @safe function 'vibe.stream.tls.createTLSContext.createBotanContext' cannot call @system constructor 'vibe.stream.botan.BotanTLSContext.this'
```
> Mark BotanTLSContext constructor as trusted

- redis/vibe/db/redis/sessionstore.d
When reading the description of expirationTime, it says "The duration without access after which a session expires." To me, this means if you continue to "access" the session, it resets the duration. However, in the implementation, it only sets the TTL once, when the session is created. This means that accessing it does not re-up the timeout.
This fixes that, so now every time you open the session, it also resets the timeout. This is what I would expect session expiration to mean.
> Re-up TTL when opening an existing session

- redis/vibe/db/redis/sessionstore.d
Currently when using redis for sessions, the default key is the session id, and the default value is the session id. The session id's length is 86 characters long. This means that for every session, redis will require 86 * 3 characters minimum of memory, instead of just 86 characters. The key name and data isn't important at all. It's just a minimal default key so the session can be created (redis does not allow empty hashmaps).
This replaces the very long name and value with a small one. While it may not make a huge difference (comes out to about 16.5MB difference if you have 100k sessions), it seems unnecessarily wasteful. In my case, at least, this "default" key is more than 2x larger than all the session data I am storing.
> Remove costly default key

- core/vibe/internal/allocator.d
- utils/vibe/internal/utilallocator.d
- utils/vibe/utils/array.d
Since 2.074.0 I could observe at least three regressions:
This is a dirty workaround against the ISharedAllocator changes and allows vibe.d to be built again.
> Fix Vibe.d nightly (phobos/5355: ISharedAllocator)

- core/vibe/internal/allocator.d
- data/vibe/data/bson.d
- http/vibe/http/client.d
- http/vibe/http/server.d
- inet/vibe/inet/message.d
- stream/vibe/stream/memory.d
- stream/vibe/stream/openssl.d
- stream/vibe/stream/operations.d
- utils/vibe/internal/utilallocator.d
- utils/vibe/utils/array.d
- utils/vibe/utils/hashmap.d
Just to avoid confusion or name clashes with the original from `std.experimental.allocator`. Also uses lazy initialization to avoid potential module constructor cycles (not currently an issue!).
> Rename the internal processAllocator to vibeThreadAllocator.

- http/vibe/http/server.d
https://github.com/rejectedsoftware/vibe.d/pull/1677
FWIW in theory JSON can be encoded in UTF-16 and UTF-32 (see references below), but the current implementation doesn't handle this as well, it just silently assumes UTF-8.
References
---------------
https://tools.ietf.org/html/rfc7159#section-8
>   JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32.  The default
encoding is UTF-8, and JSON texts that are encoded in UTF-8 are
interoperable in the sense that they will be read successfully by the
maximum number of implementations; there are many implementations
that cannot successfully read texts in other encodings (such as
UTF-16 and UTF-32).
https://www.ietf.org/rfc/rfc4627.txt
>  JSON text SHALL be encoded in Unicode.  The default encoding is
UTF-8.
>   Since the first two …
> parseJsonBody with readALLUTF8 instead of readAll + cast's

- http/vibe/http/server.d
I assume that there's probably a reason why the request parameters aren't lazily initialized, but I think the "pay once you use" is quite nice. Hence this PR is an open question whether the request parameters can be initialized on their first use. An additional benefit of using this pattern is that the returned `Json` reference is `const`.
Of course, the same pattern could be used to "lazify" other request parameters as well.
> Lazy initialization of req.json

- .codecov.yml
- .gitignore
- .travis.yml
- travis-ci.sh
This allows coverage from simple test suite as a first step.
IIRC CodeCov will send the notifications automatically, but it's better to enable them as web hook and GitHub integration (better stability).
Currently this will fail, because trailing whitespace managed to sneak in & then the test suite gets prematurely stopped.
> Allow to run CodeCov on Vibe.d

- core/vibe/core/core.d
A first step towards making `runApplication` `@safe`.
Example source code for [`getgrid`](https://linux.die.net/man/3/getgrgid):
https://github.com/bminor/glibc/blob/73dfd088936b9237599e4ab737c7ae2ea7d710e1/grp/getgrgid_r.c
https://github.com/bminor/glibc/blob/master/nss/getXXbyYY_r.c
tl;dr: It's allocated on the stack and we just check whether the returned pointer is valid.
The other libc functions are:
- [getpwuid](https://linux.die.net/man/3/getpwuid)
- [getpwnam](https://linux.die.net/man/3/getpwnam)
- [getgrnam](https://linux.die.net/man/3/getgrnam)
> Make lowerPrivileges @safe

- http/vibe/http/server.d
A couple of small things that I found by making a short pass through `http/server.d`, btw I am always positively surprised how easy Vibe.d's code is to read :+1:
> Minor cleanup in http/server.d: remove constructor + add const

- http/vibe/http/server.d
Allows to specify the bind interface and port as a single constructor argument
> Add convenience constructor to HTTPServerSettings.

- core/vibe/core/core.d
- core/vibe/core/drivers/libevent2.d
- core/vibe/core/drivers/libevent2_tcp.d
- core/vibe/core/drivers/threadedfile.d
- core/vibe/core/drivers/utils.d
- core/vibe/core/drivers/win32.d
- core/vibe/core/net.d
- crypto/vibe/crypto/cryptorand.d
- stream/vibe/stream/openssl.d
- utils/vibe/internal/win32.d
Probably not seen because no developers actively compiles Vibe.d on Windows and looked at the deprecation warnings.
See also: https://github.com/dlang/phobos/pull/5532
I am doing this blindly and relying on AppVeyor for testing.
> Remove deprecated stdc import

- http/vibe/http/client.d
- http/vibe/http/proxy.d
- changed the HTTPReverseProxySettings class to hold a destination URL instead
of (host, port)
- added reverseProxyRequest overload with URL
- updated the proxy handler logic
- made getFilteredHost() public
> Added unix domain socket support to http.proxy

- http/vibe/http/server.d
Similarly to https://github.com/rejectedsoftware/vibe.d/pull/1677
Some values are actually a bit problematic thanks to D's type concept (mutable methods!), for example consider the method `fullURL` method:
```d
@property URL fullURL()
const @safe {
URL url;
...
url.username = this.username; //  Error: mutable method vibe.http.server.HTTPServerRequest.username is not callable using a const object
url.password = this.password; //  Error: mutable method vibe.http.server.HTTPServerRequest.password is not callable using a const object
return url;
}
```
I initially had the idea to hack the type system with something like `assumeConst`:
```d
import std.traits;
private auto assumeConst(T)(T t) @trusted
if (isFunctionPointer!T || isDelegate!T)
{
enum attrs = functionAttributes!T | …
```
> More lazy loading in HTTPServerRequest

- http/vibe/http/server.d
- tests/vibe.http.server.listenHTTP/dub.sdl
- tests/vibe.http.server.listenHTTP/source/app.d
Follow-up to https://github.com/rejectedsoftware/vibe.d/pull/1810
Now that `HTTPServerSettings` accept a string, `listenHTTP` can do so as well :tada: 
Instead of adding five new overloads, I opted for templates.
> Allow listenHTTP to accept a convenience setting string

- data/vibe/data/serialization.d
This is an initial proposal for named tuple de/serialization support as associative arrays. Also part of this change is the deserialization support for the existing tuple serialization as standard arrays.
> Support for named tuple de/serialization as associative array

- web/vibe/web/web.d
These methods are pretty trivial, but convenient in practice.
> vibe.web.web: add convenience methods for status and header

- data/vibe/data/json.d
Documented that it returns Type.undefined objects if the key wasn't found.
Also added an example to the unittest.
> Json.opIndex: Document behavior if key is not found

- http/vibe/http/server.d
This makes the last two options of HTTPServerSettings lazy. As mentioned [before](https://github.com/rejectedsoftware/vibe.d/pull/1801#issue-239615384), lazy intitialization costs us `const`ness of the methods.
> Initialize parseURL and parseQueryString lazily

- data/vibe/data/serialization.d
I solved it by annotating serializeValue method and fixed all unittests so it compiles (with dmd-2.073.0).
There are some more pragma deprecation messages that can be fixed, but I wanted this to be minimal and to see if this is even acceptable.
> Fix #1673 - safety inference in tree structure of REST API

- textfilter/vibe/textfilter/urlencode.d
In case of no escape sequences, the input string will be returned. This also replaces the similar logic for urlEncode by a generic approach. See also #1635.
> Let urlDecode return a slice if possible.

- core/vibe/core/drivers/libasync.d
- core/vibe/core/drivers/libevent2.d
- core/vibe/core/drivers/win32.d
- core/vibe/core/net.d
Adds necessary functions on UdpConnection to control basic IP multicast.
I am working on getting a PR into druntime to get rid of the ugly conditional imports.
> libevent udp ip multicast implementation

- http/vibe/http/client.d
- http/vibe/http/server.d
- stream/vibe/stream/wrapper.d
This is closer to the typical ~1500 byte MTU of ethernet connections and already reduces the protocol overhead for range sourced bodies considerably. In the future, the buffer should be even larger, but the required memory shouldn't be allocated on the stack to keep the typical stack use per request low (avoids committing more memory pages for the stack) . A per-thread freelist or the request allocator could be used instead.
> Use larger streamOutputRange chunk size in the HTTP package.

- http/vibe/http/websockets.d
> Assemble frames in OutgoingWebSocketMessage in a single buffer.

- http/vibe/http/websockets.d
- tests/not-runnable/vibe.http.websocket-autobahn-client/.gitignore
- tests/not-runnable/vibe.http.websocket-autobahn-client/dub.json
- tests/not-runnable/vibe.http.websocket-autobahn-client/source/app.d
- travis-ci.sh
This is a rebased version of #1534, adjusted for the changes in #1792.
> Improve web sockets and add autobahn test suite client

- core/vibe/core/drivers/libasync.d
See the discussion in #1835. Libasync now uses the default thread pool of `std.parallelism`, which is shut down automatically.
> Remove explicit thread destruction code in the libasync driver.

- mongodb/vibe/db/mongo/sasl.d
If `connectMongo` with SASL (e.g. SCRAM) is called in a static shared constructor, it will nicely segfault.
> Initialize variables in shared static this()

- mongodb/vibe/db/mongo/connection.d
- mongodb/vibe/db/mongo/mongo.d
Added the fallback just to be sure to avoid breakage.
> Fix #1785 - Use SCRAM-SHA-1 as default for MongoDB

- http/vibe/http/websockets.d
- Fixes server initiated PINGs to be properly masked
- Fixes the detection logic for matching PONG messages
- Uses send() to send control messages instead of manually assembling frames
- Streamlines processing of control messages
> Fix WebSocket ping logic. Fixes #1471.

- web/vibe/web/i18n.d
there is now a function to replicate the default behaviour of a translation context (as returning null simply uses the first element in languages) + the cases that were advertised in the examples (like rewriting en_GB to en_US if only that is available) actually work now and are unittested.
Validation for checking if there are ambigious languages in the allowed languages is still not implemented, but documented how it should be done to avoid issues.
I couldn't find the examples (http://vibed.org/docs#web-localization) in the repository so I didn't change the documentation there that now you can also use `en-US` or simply `en` (generic international fallback english) as language tags, but I added it to the `translationContext` documentation.
> better i18n Accept-Language parsing to properly support examples (+ as standalone function)

- web/vibe/web/web.d
Because s_requestContext was private you couldn't really get the language that was chosen without including the request as argument and then calling the translation context's determine language function.
> Added web interface language() property

- core/vibe/core/drivers/utils.d
SO_REUSEPORT is defined in core.sys.posix.sys.socket by https://github.com/dlang/druntime/pull/1879, producing an ambiguity error.
Without an import, what symbol does the existing version check against?
> fix check for redefining symbol SO_REUSEPORT

- http/vibe/http/router.d
See also: https://github.com/rejectedsoftware/vibe.d/issues/1866
> Fix 1866 - router.match doesn't work with delegates anymore

- http/vibe/http/server.d
fix #1872, now parsing files works again
> Use raw Content-Type in parseFormAndFiles

- data/vibe/data/serialization.d
This might help https://github.com/dlang/dmd/pull/6998 to pass the tests.
Is the mangling only used for the test in vibe.d or does a change also have an impact on real serialized data?
> make tests agnostic to the mangling of string[string]

- core/vibe/core/log.d
There is now also a fallback using the not-fully-qualified hostname on windows & posix and using the fully qualified one on Windows
> proper hostname for SyslogLogger on windows + fallback

- http/vibe/http/server.d
#1875 actually introduced a bug where the server wouldn't accept any requests without Content-Type anymore
> Fix server not allowing requests without Content-Type

- mongodb/vibe/db/mongo/cursor.d
`m_currentDoc` was relative to the chunk start and not relative to the document start. I dislike the current mongodb testing system by manually calling these `test()` functions inside unittests when changing something, that basically destroys the whole reason of automated tests. Can't you install mongodb on the travis & appveyor test servers?
> Fix #967 & made MongoCursor.limit/skip safe

- .gitignore
- .travis.yml
- core/meson.build
- crypto/meson.build
- data/meson.build
- http/meson.build
- inet/meson.build
- mail/meson.build
- meson.build
- mongodb/meson.build
- redis/meson.build
- stream/meson.build
- textfilter/meson.build
- tls/meson.build
- travis-ci.sh
- utils/meson.build
- web/meson.build
The Meson configuration is modularized as well now - there are some improvements that can be done (the files are a bit verbose), and maybe there are even some issues left, but I will find most of those when packaging the new version for Debian.
I also enabled CI for the builds.
> Make Meson work with 0.8.x

- core/vibe/core/drivers/libevent2.d
std.c.* has been deprecated for a while and is about to be removed from
Phobos. The bindings that vibe.d was using that were there and still
missing from druntime have been added, and vibe.d needs to be updated to
use them.
I would have just continued to import `std.c.*.socket` for older versions, but unfortunately, at the moment, it looks like the way that `__VERSION__` is handled in dmd master is that it matches the last major release and not the release that it will be for. The druntime bindings did not quite manage to make it into 2.076 unfortunately, and the `std.c.*` modules were actually scheduled to be removed back in June. So, they probably won't be in master much longer. So, using them as long as `__VERSION__` is less than 2077 will fail thanks to the fact that `__VERSION__` is …
> Fix it so that std.c.* is no longer required.

- .gitignore
- http/meson.build
- lib/subprojects/diet.wrap
- meson.build
- web/meson.build
Hi!
This makes the Meson build-system automatically fetch the latest Git copy of Diet in case no Diet is found on the system already. This resolves issue #1898
Please do not merge this until https://github.com/rejectedsoftware/diet-ng/pull/39 is merged and I have adjusted the Git URL in this patch to point to upstream Diet instead of my forked copy!
> meson: Always build with Diet

- inet/meson.build
This resolves a stupid copy&paste issue that resulted in a wrong/misnamed pkg-config file being generated and installed.
> meson: Fix typo

- http/vibe/http/common.d
This adds Duration/SysTime overloads for expires/maxAge properties and adds an expires method that sets both attributes at the same time. The members of the Cookie class also get documentation comments.
Fixes #1701.
> Add better means to set cookie expiry times

- core/vibe/core/args.d
This allows to handle command line args before the vibe.d cmd hanlder kicks in.
This is needed if a user for example wants to handle --help|-h by himself or wants to use a custom parser.
> setCommandLineArgs

- tls/vibe/stream/openssl.d
- apparently no longer works with OpenSSL 1.1, use the proper accessor
X509_STORE_CTX_get_current_cert instead
> fix direct access of X509_STORE field with VibeUseOpenSSL11

- .travis.yml
@s-ludwig:
> Travis builds start to fail, because of something that changed with their system packaging: https://travis-ci.org/vibe-d/vibe.d/jobs/274722352
>
> Do you know of a more portable way to access pip/pip3?
Annoying... They should just make a base image based on a current Ubuntu release (like, the last LTS, not a prehistoric one) test it until they like it and then throw it out without modifying much (new browsers and security/integration fixes etc. are exceptions).
They warned about the image changing, but this particular change is missing from the changelog :P https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/
Anyway, I was playing around with this a little, but Travis seems to be on low capacity at time, so I am not sure if this patch works (we'll see).
> travis: Workaround for pip install Travis issue

- data/vibe/data/json.d
A very simple translation of `skipNumber` to the range API.
> improve json range support

- http/vibe/http/dist.d
- http/vibe/http/server.d
This allows accepting incoming HTTP connections on a custom transport, such as a pre-established TCP connection, or a USDS socket.
> Make handleHTTPConnection public

- web/vibe/web/common.d
- web/vibe/web/internal/rest/common.d
- web/vibe/web/web.d
It used to be supported by the web interface generator. This commit moves it to vibe.web.common.
> Support the noRoute attribute in the REST interface generator.

- web/vibe/web/web.d
> Add properties for accessing the current request and response of a web interface

- web/vibe/web/auth.d
- web/vibe/web/internal/rest/common.d
Previously only classes were inspected, leading to authentication parameters being wrongly qualified as body parameters in the client generator (which just gets the interface).
> Accept requiresAuth annotations on REST interfaces, too.

- core/vibe/core/path.d
- http/vibe/http/server.d
See #1628 and #1635 - this provides a suitable base for implementing a more correct router matching functionality.
> Implement HTTPServerRequest.requestPath as a replacement for .path.

- utils/vibe/utils/dictionarylist.d
I had some issues with this static assert generating undefined references when building with -inline (in 'profile' builds) with dmd.
I created an issue on the dmd bug tracker (See https://issues.dlang.org/show_bug.cgi?id=17895) but this fixes my issue without having to wait for them to fix it and I don't see why this assert couldn't be a unit test instead.
> Replace static assert in with unittest

- .travis.yml
- travis-ci.sh
Meson broke its wrap support in the 0.43 release, this PR excludes the faulty version from being used and also updates the Ninja version used for building.
This error is fixed in newer Meson versions, see https://github.com/mesonbuild/meson/commit/36d85db5d41b1f3a8e3f13a1680d1758353b23f7 for details.
Cheers,
Matthias
> Fix Meson build

- tls/vibe/stream/openssl.d
> Revert making sk_num/sk_value an alias to fix the linker error mentioned in #1958.

- tls/vibe/stream/botan.d
> Replace assertion from BotanTLSStream with a warning message.

- utils/vibe/internal/utilallocator.d
After this PR in Phobos, https://github.com/dlang/phobos/pull/5831, `IAllocator`s `owns` must take a `const void[]`
> IAllocator owns takes const void[]

- core/vibe/core/args.d
- tests/args/test.sh
As vibe.d is using low-level Runtime.args from which the `--DRT-` arguments are not filtered.
> ignore druntime arguments

- web/vibe/web/i18n.d
- web/vibe/web/web.d
Redo of #1869 because that one was on master and I accidentally updated that branch
> Added support for i18n language arrays

- core/vibe/core/drivers/libevent2.d
- core/vibe/core/drivers/utils.d
> Set SO_REUSEPORT for the libevent driver on BSD/macOS, too.

- examples/http_forward_proxy/dub.json
- examples/http_forward_proxy/source/app.d
- http/vibe/http/proxy.d
Overview of changes:
- Generalized 'HTTPReverseProxySettings' into 'HTTPProxySettings' and added a bool for setting reverse proxy mode.
- Moved the 'handleRequest' code out of 'reverseProxyRequest' and into a general 'proxyRequest' function.
- Created a 'forwardProxyRequest' function and updated the 'reverseProxyRequest' function to then call into 'proxyRequest' with the properly set 'HTTPProxySettings' where necessary.
- Created new 'listenHTTPForwardProxy' methods to compliment the existing 'listenHTTPReverseProxy' functions.
Testing:
All unit tests pass. I tested both the existing 'http_reverse_proxy' example and the new 'http_forward_proxy' example to ensure they were both working. NOTE*: the 'http_forward_proxy' example will only work with HTTP sites, not HTTPS. Trying to access an …
> Added forward proxy support  and included an example

- http/vibe/http/proxy.d
There were two issues:
- The destination resource ("host:port") was not parsed correctly
- The response header was missing
See #1893.
> Fix proxy CONNECT request handling.

- http/vibe/http/server.d
this makes it possible for the user to define their own custom render functions with the new diet renderer (namely you can create a render function using compileHTMLDietString now)
Reboot of #1730
> Make DefaultFilters public & rename to DefaultDietFilters

- tls/vibe/stream/openssl.d
Without this patch, there are compilation errors with undefined
references when trying to seen HTTPS connections when using
OpenSSL1.1.x.  You can duplicate this issue by trying
`requestHTTP("https://google.com").toString.writeln;`
I've seen this issue occur and be fixed with this patch on both
Fedora 26 and 27.
> Fix support for outbound SSL w/ SSL1.1.x

- http/vibe/http/websockets.d
This enum and function provide access to the defined websocket close
codes and will also generate the reason string based off of the code if
one isn't already defined.  This saves library users from having to look
up documentation.
> Added spec defined websocket close enum

- http/vibe/http/proxy.d
- http/vibe/http/server.d
A hack to start triggering deprecation for `HTTPServerOption`.
I assumed that if we go this way, #1946 would have been incorporated.
> Start to deprecate HTTPServerOption

- core/vibe/core/core.d
The initial code was not very portable across various C run-time libs, for example uClibc doesn't provide the `get_nprocs` function
> Portable way to get the processor count on Linux

- appveyor.yml
Due to some change, the MongoDB test fails/hangs currently.
> Explicitly request "mongodb" service for AppVeyor builds.

- core/vibe/core/core.d
We don't have to call sysconf(3) every workerThreadConut calls.
> Use std.parallelism.totalCPUs, it's optimized

- redis/vibe/db/redis/types.d
Hello,
A fix as per title.
Thank you very much for dub and vibe.d!
Best regards,
Geoffrey
> Fix RedisHash!int.opIndexOpAssign

- utils/vibe/utils/dictionarylist.d
Turns out that the fix for issue #2004 is trivial: the default argument just needs to be specified with the `inout` qualifier.
> Fix issue 2004: DictionaryList.get doesn't work with class/interface

- data/vibe/data/serialization.d
A warning is emitted because this workaround breaks safety inference.
Ping @timotheecour (just FYI)
> Work around compile error in the serialization system. Fixes #1991.

- web/vibe/web/rest.d
- e.g. b/c of a custom fromRepresentation method
Unfortunately not easily possible to give a more exact error message.
> unbreak and deprecate REST return types with unsafe serialization

- data/vibe/data/json.d
According to Callgrind this function is the heavies one in the process of json serialization of string-heavy objects. This pull request is aimed to improve it's performance a little by reducing the frequency of dst.put calls and getting rid of lastch reassignment on every iteration. This reduces the time (exclusive) spent in this function by ~2% and reduces the number of "put" invocations considerably, giving ~10% improvement of total (inclusive) time on my test case.   
Also, are you sure about that 
```
pos -= 1;
```
in escape_unicode version of this function? I'm getting an infinite loop feeling.
> small optimization for jsonEscape

- http/vibe/http/fileserver.d
Caching as an optimization with possibly undesired side-effects should be enabled consciously instead of being the default.
> Disable the default caching of the HTTP file server.

- core/vibe/core/drivers/libevent2.d
- Also do a little formatting cleanup
- Add static assert to prevent compilation when IP_ADD_MEMBERSHIP, IP_MULTICAST_LOOP are missing (not sure if this is preferred or not)
> Fix compilation on DragonFlyBSD

- appveyor.yml
We should really start to use a common install script for AppVeyor.
> Bump DUB version used on AppVeyor to 1.7.1

- inet/vibe/inet/urltransfer.d
- connection should be closed IFF HTTPClient is owned by download
- introduced in 90b2fbcd685bf227f6afa58074c85806c61abbc0
> fix leakage of connections

- tests/tcp/source/app.d
- hides any real backtrace
- test seem flaky (at least failed once on ci.dlang.org, see #2054)
> remove (pointless?) scope(failure) assert(false)

- http/vibe/http/router.d
Uses manual memory management for `MatchGraphBuilder` to avoid fragmenting the GC heap, which previously lead to huge process memory usage (See #1359). As a matter of fact, this also reduces the peak memory usage while building the match graph of the `URLRouter`.
> Optimize memory issues in URLRouter. Fixes #1359.

- http/vibe/http/proxy.d
This is a regression introduced by the forward proxy functionality.
> Fix wrong proxy mode when creating HTTPReverseProxySettings.

- mongodb/vibe/db/mongo/collection.d
- mongodb/vibe/db/mongo/connection.d
- mongodb/vibe/db/mongo/cursor.d
- tests/mongodb/source/app.d
This PR replaces the aggregate function and adds support for options and makes MongoCursor more extensible with support for any cursors instead of only `find` cursors
fix #2036, fix #1718
Tested with latest MongoDB 3.2, 3.4, 3.6
> Fix mongodb 3.6 aggregate

- examples/bench-http-request/source/app.d
Yet another deprecation removed.
Note that `std.getopt` doesn't support `shared`.
See also: https://github.com/dlang/dmd/pull/7816
> Fix deprecations: use atomicOp in examples/bench-http-request

- http/vibe/http/client.d
Allows to customize the TLS context on a per-client or per-request basis instead of just globally using HTTPClient.setTLSContextSetup.
> Add HTTPClientSettings.tlsContextSetup.

- .travis.yml
- travis-ci.sh
With the Meson 0.44.1 release, all the bugs and annoyances that were happening before regarding subprojects and subproject_dir locations as well as DMD support should be fixed now (and even better: they have a unittest in Meson now).
So, it's safe to re-enable Meson, if this PR builds successfully on the CI.
> Enable Meson on the CI again, now that it's fixed

- data/vibe/data/json.d
fix #1465 
But for some reason I can't get the serializer/deserializer to work. If I replace the `@safe` with trusted in the workaround code [here](https://github.com/rejectedsoftware/vibe.d/blob/master/data/vibe/data/serialization.d#L354) serializing works. I made the JSONValue serialization exactly the same as Json serialization, just with the call to toJSONValue/fromJSONValue but it still seems to fail with seemingly unrelated issues (some strange inout issue in the deserializer). Any idea how to make the (de)serializer work?
> Add Json.toJSONValue & Json.fromJSONValue

- core/vibe/core/path.d
Slash behavior originally introduced here vibe-d/vibe.d@970a022#diff-3620332feace439ec637b023bc2e7a01R262, and apparently broken here vibe-d/vibe.d@344fe34#diff-47d6be40e29a186df00d5f3bfad92671R36.
The weird usage of Path for URLs and file paths on Windows makes this difficult to handle properly (though `/` and `\` usage should be mut-ex IIRC). No idea how much impact this breaking change would have. Any suggestion for a better migration path?
> preserve trailing back-slashes in NativePath

- examples/.travis.run
- examples/http_request_digest/dub.json
- examples/http_request_digest/source/app.d
- http/vibe/http/auth/digest_auth.d
Added the method to generate digest authentication request header from the response digest parameters.
Also added the example to test it.
It works for the start but I would like to solve also the problem with `cnonce` and `nc` parameters.
If I understand it correctly, cnonce should be the same if the server uses the previous nonce and nc just incremented in following client requests.
For that it is needed to store the values somewhere on the client.
I think that maybe if we add Variant context storage to the HTTPClient and make it accessible from the HTTPClientRequest and HTTPClientResponse it can be used for this as HTTPClient is reused from the pool. Also it should be cleared when the connection is closed.
Is this the correct way of thinking to provide facilities to implement digest …
> Add methods to support client request digest authentication

- tests/rest/source/app.d
- tests/restclient/source/app.d
- tests/restcollections/source/app.d
- tests/tcp/source/app.d
- tests/tcpproxy/source/app.d
- tests/vibe.core.net.1726/source/app.d
- tests/vibe.http.client.1389/source/app.d
- tests/vibe.http.client.1426/source/app.d
- tests/vibe.http.server.1388/source/app.d
- tests/vibe.http.server.1721/source/app.d
- tests/vibe.http.server.host-header/source/app.d
- tests/vibe.http.server.listenHTTP/source/app.d
- tests/vibe.http.websocket/source/app.d
- tests/vibe.web.rest.1125/source/app.d
- tests/vibe.web.rest.1140/source/app.d
- tests/vibe.web.rest.1230/source/app.d
- tests/vibe.web.rest.1922/source/app.d
- tests/vibe.web.rest.auth/source/app.d
- tests/vibe.web.web.auth/source/app.d
- tests/vibe.web.web/source/app.d
- for obvious reasons
- dropped IPv6 binds as requestHTTP to IPv6 addresses doesn't work (#2080)
(also IPv6 support should be tested once, not everywhere)
> run tests on ephemeral ports

- data/vibe/data/json.d
This allows other similar conversions to be implemented later, in particular for `stdx.data.json`. It also enables `json.to!JSONValue` and `jsonvalue.to!JSON` conversions.
See #1904.
> Convert (to/from)JSONValue to opCast/constructor.

- http/vibe/http/server.d
Got introduced with the addition of vibe-core compatibility.
> Fix a regression in the HTTPServerRequest.rootDir property.

- .travis.yml
- appveyor.yml
Should reduce this redundancy from four to two CI runs:
> Only build master on Travis

- redis/vibe/db/redis/types.d
All supported redis values now work as per the test below:
```d
auto db = connectRedis("127.0.0.1").getDatabase(0);
db.getAsList("test_list").remove();
db.getAsSet("test_set").remove();
db.getAsZSet("test_zset").remove();
db.getAsHash("test_hash").remove();
db.getAsString("test_string").remove();
```
> Fix: forward RedisValue methods hidden in redis types by overloads

- tests/vibe.http.websocket/source/app.d
Closes #2104 - the actual bug fix is https://github.com/vibe-d/eventcore/pull/55
> Test for proper WebSocket connection state.

- http/vibe/http/client.d
Determines the flag after the HTTP version and "Connection" header have been set to their final values.
> Fix closing of user-triggered non-keepalive connections.

- web/vibe/web/common.d
Using a string enum as parameter in a web interface results in build failure.
Example:
```d
import vibe.d;
enum StrEnum{
a = "hello", b = "world"
}
class WebIface{
void getTest(StrEnum param){}
}
void main(){
import std.traits;
pragma(msg, "StrEnum is dynamic array: ", isDynamicArray!StrEnum);
pragma(msg, "StrEnum is some string: ", isSomeString!StrEnum);
auto router = new URLRouter;
router.registerWebInterface(new WebIface);
}
```
Outputs:
```
StrEnum is dynamic array: true
StrEnum is some string: false
vibe-d-0.8.3-rc.1/vibe-d/web/vibe/web/common.d(799,9): Error: cannot modify `immutable` expression `dst`
vibe-d-0.8.3-rc.1/vibe-d/web/vibe/web/common.d(773,15): Error: template instance `vibe.web.common.setVoid!(immutable(char), immutable(char))` error instantiating …
```
> String enum as form parameter is treated as an array of `immutable(char)`

- tls/vibe/stream/openssl.d
Fixes bogus "Reading from TLS stream was unsuccessful with ret 0" errors.
> Properly handle TLS disconnects in OpenSSLStream.leastSize.

- source/vibe/stream/openssl.d
This is for 0.7.32 and is important due to the imminent european GDPR deadline...
The same bug is also present in master.
> Fix openssl cert peer validation

- data/vibe/data/json.d
This small fix improves efficiency of Json object field assignment by reusing an AA  bin pointer.
> reduce hash calculations in json opIndex

- web/vibe/web/rest.d
This can be used to modify outgoing request headers based on the content of the request body.
> Add RestInterfaceClient.requestBodyFilter property.

- redis/vibe/db/redis/redis.d
For reference: many PaaS providers supply the Redis password directly in the URL and it took me quite a bit to figure out that the Redis implementation simply doesn't look at the `password` part of the Redis URI.
Regarding this PR, I am not sure how add test for this that work on all machines. Happy about ideas.
I copied the interesting bits from the [spec](https://www.iana.org/assignments/uri-schemes/prov/redis) for future readers.
BTW what do you think about adding a convenient UFCS-friendly way to build URLs?
I would love to write: `"https://google.com".url`, but then again `url` is a very commonly used variable.
> Support full Redis IANA URI scheme

- examples/bench-http-request/source/app.d
- examples/bench-mongodb/source/app.d
- examples/bench-urlrouter/source/app.d
- examples/file_operations/source/app.d
There's still a lot more going on. It might be worthwhile to compile all tests and examples with `-de`?
> Fix a few deprecation warnings

- web/vibe/web/web.d
Provide the same API as  `HTTPServerResponse.redirect`
> Make vibe.web.web.redirect similar to HTTPServerResponse.redirect

- tests/vibe.web.web/source/app.d
- web/vibe/web/web.d
> vibe.web.web: Allow to return strings

- http/vibe/http/common.d
- http/vibe/http/websockets.d
Low-hanging fruits in terms of GC disturbance.
> asLowerCase and lazy splitter for small part of header processing

- .travis.yml
Used a forked version of the installer script as the Travis failures get super-annoying and https://github.com/dlang/installer/pull/301 isn't moving anywhere.
Once it's merged, these lines could be dropped and replaced with e.g. `- dmd-2.073.1+dub` (2.073.1 + newest dub compiler)
> Install the newest version of dub to avoid random network failures

- core/vibe/core/path.d
Prepends an empty path segment for absolute paths, so that the segment representation of the path is the same as for vibe-core.
See also dlang/dub-registry#318.
> Make the legacy Path.bySegment semantically compatible with vibe-core.

- .travis.yml
- appveyor.yml
- source/vibe/core/drivers/utils.d
- source/vibe/data/serialization.d
- tests/vibe.core.net.1726/source/app.d
- tests/vibe.http.server.1721/source/app.d
- tests/vibe.http.server.host-header/source/app.d
- travis-ci.sh
Excluding the intermediate versions to avoid unnecessary CI job bloat.
> Test on DMD 2.079.0 and LDC 1.8.0.

- source/vibe/core/drivers/utils.d
The import wasn't properly included. Was fixed in the master branch, but not the 0.7.x branch.
Identical to #1861
> Fix issue with building on dmd 2.079

- data/vibe/data/json.d
- utils/vibe/internal/rangeutil.d
> Fix serialization of const/mutable and wide character strings

- data/vibe/data/json.d
This is a slightly modified version of #2088 that restricts the UUID addition to just the serialization logic. No public `UUID` constructor for `Json` gets added.
Closes #2088.
> Add UUID serialization support

- textfilter/vibe/textfilter/markdown.d
Whenever an "at" character was in an auto URL, the contents were treated as an e-mail address. This was even the case for URLs such as "http://foo/bar@baz".
> Fix bogus mailto links generated by the Markdown parser.

- http/vibe/http/server.d
- tests/vibe.http.server.empty-json/dub.sdl
- tests/vibe.http.server.empty-json/source/app.d
If `req.json` is called on an empty Json body, it throws an error message which
is rather hard to understand for the casual observer:
```
core.exception.AssertError@/usr/include/dlang/dmd/std/typecons.d(2583): Called `get' on null Nullable!Json.
----------------
??:? _d_assert_msg [0xb539aeea]
??:? inout pure nothrow ref @property @nogc @safe inout(vibe.data.json.Json) std.typecons.Nullable!(vibe.data.json.Json).Nullable.get() [0xb5224d99]
??:? ref @property @safe vibe.data.json.Json vibe.http.server.HTTPServerRequest.json() [0xb521431d]
??:? void app.handler(scope vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse) [0xb51e4b4e]
??:? @trusted void vibe.http.server.listenHTTP!(vibe.http.server.HTTPServerSettings).listenHTTP(vibe.http.server.HTTPServerSettings, void …
```
> http.server: handle an empty Json body

- web/vibe/web/rest.d
They cant be deserialized by json deserializer directly without quotes so I've added direct type condition
> Allow UUIDs as path parameters in REST

- data/vibe/data/bson.d
Subj. This PR is needed for [druntime#2243](https://github.com/dlang/druntime/pull/2243)
If it is possible, make a new tag if this will be approved, please.
> fix Bson.opEquals: order of object keys is not determined

- http/vibe/http/client.d
- web/vibe/web/rest.d
Added missing fields copy in RestInterfaceSettings.dup().
Without this, setting `errorHandler` callback will not work because
of this in `module vibe.web.internal.rest.common:L118`
```D
this.settings = settings ? settings.dup : new RestInterfaceSettings;
```
> Fix RestInterfaceSettings.dup() for errorHandler callback

- data/vibe/data/bson.d
It was not possible to pass an alias of m_data with const qualifier into a function that mutates the reference. Now passing a full slice instead.
Also added an unit test
> Fix issue #2212: Bson.get!BsonRegex does not compile

- examples/http_server/dub.json
- examples/http_server/dub.sdl
- examples/http_server/source/app.d
- examples/http_static_server/dub.json
- examples/http_static_server/dub.sdl
- examples/http_static_server/source/app.d
- examples/https_server/dub.json
- examples/https_server/dub.sdl
- examples/https_server/source/app.d
- Uses a custom main instead of relying on the default implementation
- Stops the HTTP listener on shutdown to avoid socket leak warnings
> Fix/modernize a few HTTP server examples.

- tls/vibe/stream/openssl.d
Use new BIO methods
more error handling
Also changes minimum protocol version to new API
Split the error handling API to be more usable
Fix IO error message
fix #2214
> Fix OpenSSL 1.1.1 by using new APIs

- core/vibe/core/log.d
As seen in [documentation](http://man7.org/linux/man-pages/man2/uname.2.html) `nodename` is `char[]` of unspecified size and string is null terminated.
There is specified size of 65 in [druntime](https://github.com/dlang/druntime/blob/a59c3832fc00ab127018d9a570ba03520437524f/src/core/sys/posix/sys/utsname.d#L22).
But `to!string` on the char array doesn't handle null terminated string but just returns it in a full length with nulls.
I've found this out on one of the servers where something strange was logged and it was exactly 65 chars in length.
Fixed it using `std.string.fromStringz`.
**Note**: This should be fixed in [vibe-core](https://github.com/vibe-d/vibe-core/blob/6ca6dd16d4f89c1a8d3bb89fa58d56cf466d70e6/source/vibe/core/log.d#L739) too
> fix returning hostname from uname on posix

- tls/vibe/stream/openssl.d
The current `alpn()` method used to retrieve the negotiated ALPN protocol does not retun a well-formed string but causes a memory corruption, since the `SSL_get0_alpn_selected` function expects a `NULL` pointer. From `man SSL_get0_alpn_selected`:
```
void
SSL_get0_alpn_selected(const SSL *ssl, const unsigned char **data, unsigned int *len);
...
SSL_get0_alpn_selected() returns a pointer to the selected protocol in data with length len.  It is
not NUL-terminated.  data is set to NULL and len is set to 0 if no protocol has been selected.
data must not be freed.
```
This bug can be reproduced by initalizing an OpenSSLStream and call its `alpn()` method after a TLS handshake has been completed and `alpnCallback` has been invoked.
The proposed solution is to use a `const(ubyte)*` pointer which …
> Fix OpenSSL ALPN array corruption

- .travis.yml
Unfortunately, the tests have been broken for a while now due to dependency issues in the stdx-allocator package. Now the pyenv command also fails, meaning that all test builds finally got broken. This is a band-aid fix to get the test pipeline going again.
> Disable the Meson tests.

- tls/vibe/stream/openssl.d
While testing the HTTP/2 module there were some cases in which reading from a `OpenSSLStream` failed with a segmentation fault. This is due to the fact that the underlying `SSLState` gets freed when receiving a `close_notify` alert from TLS.
The `SIGSEV` was caused by the usage of a `null` `m_tls` state which would be passed to `SSL_read` and `SSL_peek`, resulting in a memory corruption. An easy fix for this is to add checks for `null` in both `OpenSSLStream.read()` and `OpenSSLStream.leastSize()` and since both methods are supposed to return an integral, return `0` instead.
> Fix segmentation fault on SSL_read due to null SSLState

- stream/vibe/stream/stdio.d
Its often useful to get access to the underlying data for interacting with other APIs such as `std.process`.
> Add stdFile property to StdFileStream

- data/vibe/data/json.d
> Fix Json array clone

- web/vibe/web/common.d
I'm currently building a angular service generator.
This is done by introspecting rest interfaces.
To get the parameter names right, it needs to look at the UDAs, and more
specifically at WebParamAttribute.
> Made WebParamAttribute public to allow rest introspection

- data/vibe/data/bson.d
Otherwise right now when using the Bson constructor taking a date with null timezone, it will take the local time. When the local time timezone is negative and you want to convert back from BsonDate to SysTime to Date, you will be a day behind than what you originally input because you can only convert to SysTime using UTC.
> Add BsonDate.toSysTime(tz) overload

- core/vibe/core/drivers/libevent2.d
Caching at this layer is not going to work, because we don't know the TTL.
Because of this cache, you might be in a situation where you try to connect to a host that is no longer there, or worse, you connect to a host that is not what you expected.
> Remove DNS cache

- tls/dub.sdl
only write to the data path (and with it update the modification date) when openssl version changes
> Fix dub recompiling on every compilation

- http/vibe/http/server.d
- inet/vibe/inet/webform.d
- web/vibe/web/common.d
Fixes #1984 
A few notes about this:
1. I didn't see any unittests to modify, all the unittests in here just check for compilation issues.
2. This *should* work with arrays nested in structs, but not arrays of structs (unless the struct is completely serialized in one go). This is intentional, as the appending depends completely on serializing the whole thing at once.
3. DictionaryList requires a `@safe` delegate for getAll, but there's a lot of unsafe things within the `webConvTo` function, so I couldn't do it. TBH, I'm not sure its really the right approach to use the `=void`, and use that very unsafe copy mechanism, but I'm assuming there's a good reason.
Please double check the test I wrote for when things can't be serialized. I think I got it right, but I didn't test.
> Add handling of arrays in form/query data like 'arr[]'

- web/vibe/web/common.d
To build a function that can call a rest interfaces and provide a JWT,
I needed to introspect on the PathAttribute.
> Make PathAttribute public for introspection

- web/vibe/web/web.d
Followup to #2247 to document new behaviors. No code changes here, just ddoc changes.
> Add documentation for new array handling mechanisms.

- core/vibe/core/drivers/libevent2_tcp.d
- http/vibe/http/client.d
- http/vibe/http/server.d
- http/vibe/http/websockets.d
- tests/vibe.http.websocket.2169/dub.sdl
- tests/vibe.http.websocket.2169/source/app.d
Fixes #2169. This is a full solution that also fixes a socket descriptor leak and supercedes the workaround in #2172.
> Fix multiple concurrent websocket connects failing

- web/vibe/web/common.d
- web/vibe/web/web.d
Issue is with operator precedence, so the `minLength` constant was effectively always 2.
Also update docs to say that `nestedNameStyle` is only supported on the class, and not individual
methods. Seems like an odd limitation, but I'm just documenting what is present in the code currently (found out the hard way). May be something to revisit in the future, but not important at the moment.
> Fix bug with sanity check on key length.

- tls/dub.sdl
This should also make the detection work for non-build generators.
See issue #2267
> Remove explicit sourceFile directive and use preGenerateCommands instead.

- data/vibe/data/json.d
```
json.d(2149,6): Warning: Ddoc: parameter count mismatch, expected 3, got 2
```
How it passed CI?!
> Ddoc warning fix

- tls/dub.sdl
- tls/vibe/stream/openssl.d
rdmd fails intermittently with a temporary D module not being found in the temp directory. To avoid spurious CI failures and to allow the code to work on systems where rdmd is not configured correctly, these failures are now ignored and the default version is assumed.
> Ignore rdmd failures in the OpenSSL version detection.

- data/vibe/data/serialization.d
This bothered me so long that I've finally looked into it and found the issue. :)
Problem was that test for `isSafeSerializer` is using `writeValue` and `readValue` for checking and to pass correctly it requires both to compile.
In unittests, `TestSerializer` is used and works both as a serializer and a deserializer, so the test passes ok.
But that is not the case for ie `JsonStringSerializer` which has only one of those based on the provided range type.
> Fix #1941 - real fix for the workaround

- inet/vibe/inet/url.d
Properly handles UNC paths on Windows in addition to normal paths.
> Implement proper conversion between native paths and file URLs.

- http/vibe/http/client.d
- http/vibe/http/common.d
- tests/vibe.http.client.2025/dub.json
- tests/vibe.http.client.2025/source/app.d
Continuation of #2025 because I didn't have push permissions
Changes:
- algorithm implemented like specified on RFC
- ignore invalid values
- discard cookie in some cases
- normalization of some values (e.g. Domain)
- high level test
For the high level test I manually wrote the header on the server as setCookie didn't seem to work
> New support for parsing cookies

- mongodb/meson.build
- utils/meson.build
Vibe.d does not currently build with meson, this patch fixes that.
> Add missing files and dependencies to meson

- utils/vibe/utils/hashmap.d
`TypeInfo.getHash` is a virtual function call that is opaque to current D compilers. Directly using `object.hashOf` is faster.
> hashmap: increase hashing speed with integer or string keys

- http/vibe/http/common.d
- http/vibe/http/server.d
See also:
- https://www.owasp.org/index.php/SameSite
- https://medium.com/compass-security/samesite-cookie-attribute-33b3bfeaeb95
> Add new cookie option: sameSiteStrict

- core/dub.sdl
- core/vibe/core/net.d
- http/vibe/http/server.d
This integrates with recent event core `reuseAddress` flag.
It allows one to selectively disable those flags.
See https://github.com/vibe-d/vibe-core/pull/150
> Add way to disable port and address reuse

- http/vibe/http/client.d
In relation to #500, unix sockets are supported by vibe-core, not just Libevent, so I suggest we make that work out of the box. My current workaround is to put `UnixSocket` in a build.
> Make unix socket support work for vibe-core

- stream/vibe/stream/zlib.d
The process shouldn't be crashed if someone inputs bad compressed data.
> Enforce, don't assert, end of zlib data

- inet/vibe/inet/url.d
The current implementation of `URL.parse` fails when provided with an IPv6 Address. Using the latest master branch:
```D
import vibe.inet.url;
void main()
{
auto url = URL.parse("localhost:8080");
auto ipv6url = URL.parse("[1080:0:0:0:8:800:200C:417A]:8888");
}
```
The program gives the following result:
```
std.conv.ConvException@/opt/dmd-2.085/import/std/conv.d(1865): Unexpected ':' when converting from type string to type ushort
```
The code responsible for this is in `url.d` when the parser looks for  the index of the first `:` occurrence. The presence of `:` inside IPv6 addresses is not taken into account, causing a failure when trying to convert the expected port to `ushort`.
The proposed fix consider both cases by setting the index accordingly.
Edit: this can also be seen here: …
> Fix parsing of IPv6 Addresses in vibe.inet.url

- http/vibe/http/websockets.d
- tests/vibe.http.websocket.2169/source/app.d
connectWebSocket now supports both wss/ws and https/http
the connectWebSocket example is fixed by this and existing usage should work again
> Fix wss/ws websocket connection fix #2320

- .travis.yml
- README.md
- appveyor.yml
This does a couple of cleanup to the travis configuration.
See the linked blog posts for the non-D-specific parts.
> Update Travis configuration

- utils/vibe/utils/hashmap.d
Includes a unittest demonstrating code that fails without this patch.
> Fix HashMap when keys are objects that may override toHash and/or opEquals

- core/vibe/core/drivers/libevent2_tcp.d
Closes #1324 of which this is more or less a rebased version.
Supposedly fixes #1321 when using libevent.
> Free libevent TCP resources on finalize() and GC finalization.

- data/vibe/data/bson.d
- data/vibe/data/json.d
- data/vibe/data/serialization.d
- utils/vibe/internal/meta/traits.d
- utils/vibe/utils/dictionarylist.d
Also allow data to have disabled copy constructor.
> change data serialization methods to `auto ref in`

- http/vibe/http/client.d
We've needed to communicate with some Axis device which listens using HTTP/1.0 and so don't know about chunked transfer.
From the specs:
> **Content-Length:** <Ignored if ommitted or zero, or shall be set to transfer length of message body.>
> 
> When an audio stream is transmitted, the server receives a continuous flow of audio packets. The content type is only set at the beginning of the connection together with the content length that can have any value. When the connection is up and running the audio packets will come right after another without any extra information between the packets. The message body contains a block of binary data.
>
> The content length must be set to a valid size and will generate a server response for every successful playback. If the playback fails, the …
> Don't use chunked transfer with HTTP/1.0

- core/vibe/core/connectionpool.d
I've found that when the connectionFactory method throws, `ConnectionPool` keeps the lock.
My problem was with [dpq2](https://github.com/denizzzka/dpq2/blob/master/src/dpq2/connection.d#L59) postgresql connection that can throw ie when it fails to connect to the server.
I'll create PR also to vibe-core.
> unlock ConnectionPool on failure

- http/vibe/http/client.d
Fixes https://github.com/vibe-d/vibe.d/issues/1375
> Adds HTTP client timeout setting

- core/vibe/core/drivers/libevent2_tcp.d
- core/vibe/core/drivers/win32.d
- http/vibe/http/client.d
> Fixup HTTP client timeout

- http/vibe/http/fileserver.d
- web/vibe/web/rest.d
Allows to have runtime generated bodies with proper cache
For example you can cache runtime diet files with this: (with my runtime diet PR on diet-ng)
```d
import diet.html;
if (handleCacheFile(req, res, "templates/client.dt", "public"))
return;
res.writeBody(renderStaticHTMLDietFile("templates/client.dt"), "text/html; charset=UTF-8");
```
> implement more caching & public cache api

- crypto/vibe/crypto/cryptorand.d
> Fixes a const violation where atomicLoad erases const from the return value

- .travis.yml
Reduces the overall CI time on Travis CI to less than half.
> Only build old vibe-d:core configurations on the latest and oldest compiler versions.

- textfilter/vibe/textfilter/markdown.d
This is a subset of the syntax in PHP Markdown Extra, omitting the custom attributes for now.
> Add class/id attribute to the Markdown parser.

- redis/vibe/db/redis/redis.d
- redis/vibe/db/redis/sessionstore.d
- tests/redis/source/app.d
See issue #2245. This allows user code to clean up a `RedisClient` or `RedisSessionStore` before exiting the program to prevent messages of leaked eventcore drivers. Not attached to the function name, so if that needs to change, let me know.
> Allow cleanup of redis sockets to prevent event core leaking.

- http/vibe/http/server.d
The type attribute is only useful when it's not javascript
> Minor adjustment

- http/vibe/http/websockets.d
Fixes HTTP client settings handling and adds `connectWebSocketEx` with the possibility to control request headers. This replaces #2374. Note that the new function name was necessary to avoid ambiguous call errors when using the delegate based overload with an anonymous, type inferred callback.
> WebSocket improvements

- tls/vibe/stream/openssl.d
see https://github.com/ldc-developers/ldc/issues/3205
For OpenSSL 1.1.0h those definitions are conflicting.
The whole OpenSSL configuration on Windows at least is a real mess... 
https://github.com/vibe-d/vibe.d/issues/2284
> Fix compiler error with Deimos OpenSSL 1.1.0h

- inet/vibe/inet/message.d
This makes HTTP header parser more tolerant to invalid inputs in regards to line separators.
> The line terminator for message-header fields is the sequence CRLF. However, we recommend that applications, when parsing such headers, recognize a single LF as a line terminator and ignore the leading CR. 
See https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.3 for more details.
My problem is again Axis device with some CGI scripts returning something like:
```
HTTP/1.1 200 OK<CR><LF>
Date: Fri, 30 Aug 2019 15:59:02 GMT<CR><LF>
Accept-Ranges: bytes<CR><LF>
Connection: close<CR><LF>
Content-type: text/plain<LF><LF>
<body>
```
Which fails with strict parser.
> make parseRFC5322Header more tolerant on input

- http/vibe/http/websockets.d
If a `return` or `throw` is triggered in `startReader` it's possible for the connection to stay open after the `scope(exit)` call. This could mean that `waitForData` never returns.
> Make sure connection is closed after websocket reader exits

- http/vibe/http/client.d
- http/vibe/http/server.d
- http/vibe/http/status.d
- tests/vibe.http.server.informational-status/dub.sdl
- tests/vibe.http.server.informational-status/source/app.d
This adds possibility to send HTTP status messages (1xx) using `writeVoidBody` in `HTTPServerResponse`.
I've modified also the client that now can receive these messages in it's `responder` handler prior the final response.
What's not handled properly is `100 Continue` as client just sends the body right away.
I'm not so sure how to fix that as `requester` should begin to write body after `100 Continue` is received from the server in `responder`. Maybe using semaphore between `requester` and `responder`?
But this can probably be handled separately as this PR doesn't change the current behavior for that.
> HTTPServer - add support for HTTP informational status message sending

- tls/dub.sdl
```
The current way to detect OpenSSL silently fails on Mac OSX.
It is also quite crude, relying on the openssl binary.
Using a pkg-config approach first, we can support lib-only packages,
as well as provide a much better experience to most Mac users.
```
Tested on our end, works perfectly: https://travis-ci.com/bpfkorea/agora/jobs/268822369
> Improve OpenSSL version detection

- .travis.yml
- examples/bench-http-request/dub.json
- examples/bench-mongodb/dub.json
- examples/bench-urlrouter/dub.json
- examples/daytime/dub.json
- examples/download/dub.json
- examples/http_request/dub.json
- examples/http_request_digest/dub.json
- examples/json/dub.json
- examples/mongodb/dub.json
- examples/redis/dub.json
- examples/sendmail/dub.json
- examples/serialization/dub.json
- tests/args/dub.json
- tests/dirwatcher/dub.json
- tests/mongodb/insert-remove-aggregate/dub.json
- tests/redis/dub.json
- tests/restclient/dub.json
- tests/restcollections/dub.json
- tests/tcpproxy/dub.json
- tests/tls/dub.json
It is gone since v0.7.26, that is 4 years ago.
> Remove obsolete VibeCustomMain version from examples/tests

- redis/vibe/db/redis/redis.d
- tests/vibe.db.redis.redis.pr2407/dub.json
- tests/vibe.db.redis.redis.pr2407/source/app.d
This fixes two issues in redis pubsub implementation.
* The first issue (solved in 1st commit) is an infinite loop (that causes 100% CPU) that happens when the redis *server* exits while listening to pubsub messages.
The following code shows a reproduction case:
```
import vibe.db.redis.redis;
import vibe.core.core;
import vibe.core.log;
void main() {
runTask(&listenRedis);
runApplication();
}
void listenRedis() {
auto redis = connectRedis("127.0.0.1");
auto subs = redis.createSubscriber();
subs.subscribe("test");
logInfo("subscribed");
auto task = subs.listen((string channel, string message) {
logInfo("received message on %s: %s", channel, message);
});
task.join();
logInfo("done listening");
}
```
Redis server must be stopped to face the issue.
* Second issue (solved in 2nd commit) is …
> Redis pubsub fixes

- data/vibe/data/serialization.d
Fixes #1541 and is an alternative, simpler implementation of #1650
this adds an `embedNullable` UDA which specially treats std.typecons.Nullable without values as not defined. This makes it ignored during serialization.
This transparently makes the type hidden for a serializer if it's not given and thus allows special states like:
- `undefined` == Nullable!T.init (not in output at all)
- `null` == Nullable!T(null) (in output like usual for T == null)
- `value` == Nullable!T(value) (in output like usual)
Use case:
- patch structs where only the fields which should be applied are set to non-nullified values, so they allow patching to null and any other value
Doesn't repurpose `@optional` to keep backwards compatibility and avoid ambiguous definitions of "what's the ignored value" for an …
> Implement @embedNullable for serialization

- data/vibe/data/json.d
Pretty trivial. Not adding `-preview=dip25` to `dub.sdl` because it would need to be added to all subpackages to be useful (see https://github.com/dlang/dub/issues/1881).
I'm currently trying to see if we can get this enabled by default, since it's been 5 years the feature was introduced.
> data/json: Fix a DIP25 violation

- mongodb/vibe/db/mongo/collection.d
This PR adds createIndex, getIndex and improves some of the index related documentation strings.
The strings are taken (and slightly modified) info from the mongodb documentation.
This is a part of the way to getting https://github.com/vibe-d/vibe.d/issues/2200 done
> Add createIndex, getIndexes and improve docstrings

- http/vibe/http/client.d
Previously would attempt to write another request to a connection that had already been shut down by the server (server-to-client direction).
> Detect half-closed connections in the HTTP client.

- mongodb/vibe/db/mongo/client.d
- mongodb/vibe/db/mongo/collection.d
- mongodb/vibe/db/mongo/connection.d
- mongodb/vibe/db/mongo/cursor.d
- mongodb/vibe/db/mongo/mongo.d
- mongodb/vibe/db/mongo/settings.d
- tests/mongodb/insert-remove-aggregate/source/app.d
Functionality-wise this changes a few little things:
- fixes mongodb unittest (distinct giving different order now)
- add tls as alias for the ssl parameter in parsing mongodb urls
- adds authenticatePassword and authenticateSSL methods to avoid issues with wrong usage of field members
- makes makeDigest pure to avoid calling it as member, expecting stuff to happen
- x509 authentication requires a username or forces it to be omitted completely if missing on certain driver specifications
- authentication mechanism generation now follows these strict rules:
- (if set to none) if a certificate file is given & server is >= 2.6, use X509 authentication
- (if set to none) otherwise if a digest is given, check server version
- server version >= 3.0: use SCRAM-SHA-1
- otherwise use MONGODB-CR
- …
> Mongo documentation & auth improvements

- data/vibe/data/bson.d
- mongodb/vibe/db/mongo/collection.d
The new `@embedNullable` UDA can be used for serialization to ignore unset fields. This commit replaces previous manual code performing these kinds of checks to allow for easier future modification.
Also skips cursor field when explain is turned on because that's recommended to be done as a driver.
This PR also slightly extends/formats the documentation on the fields.
> Simplify MongoDB aggregate serialization

- utils/vibe/utils/hashmap.d
Allows using HashMap with key types that don't compile with move() (TaggedUnion in particular).
> HashMap move workaround.

- tls/dub.sdl
`import std;` is not used by purpose to not cause issues for older D versions.
> Replace rdmd dependency with single dub package

- appveyor.yml
- travis-ci.sh
These cause the a crash in Optlink and make the build time out.
> Remove all Optlink/OMF based CI configurations.

- tls/dub.sdl
This got previously reverted by #2401
> Default to OpenSSL 1.1.x instead of 1.0.x.

- .travis.yml
This will allow branches such as 'v1.x.x' and 'v0.9.x'.
Will merge back into master when `v0.9.2` is out (I'll add `-preview=in` support).
> Travis: Replace v0.7.x with a regex

- .travis.yml
- data/vibe/data/bson.d
- http/vibe/http/log.d
- http/vibe/http/websockets.d
- utils/vibe/utils/hashmap.d
- web/vibe/web/rest.d
This requires the following to be merged and tagged to work:
- https://github.com/vibe-d/eventcore/pull/157
- https://github.com/vibe-d/vibe-core/pull/225
- https://github.com/rejectedsoftware/diet-ng/pull/85/
> [v0.9.x] Add support for `-preview=in`

- http/vibe/http/auth/digest_auth.d
randomUUID does not use a secure RNG and exposes potential security issues, namely if sequences of randomly generated UUIDs (or other random data based on the same RNG) in other places of an application are exposed to an attacker, it becomes possible to predict the digest auth secret.
See https://forum.dlang.org/thread/zjmyxudvscfwrkrdabmt@forum.dlang.org
> Replace randomUUID by securely generated random data for digest authentication.

- http/vibe/http/fileserver.d
- http/vibe/http/status.d
Previously this would happen:
- Request:
```
Range: 10-10
```
- Response:
```
Content-Length: 0
Content-Range: 9-9/11
```
now responds with
- Response:
```
Content-Length: 1
Content-Range: 10-10/11
```
Ranges that cannot be satisfied are now also reported as an error (range start greater than the last byte or range start greater than range end).
> Fix HTTP range boundary condition handling

- http/vibe/http/client.d
I've observed that newly added condition `m_conn.waitForDataEx(0.seconds)` returns `noMoreData` even for `EAGAIN` and so leads to disconnects before the new request.
But there is still m_stream set (TLS) which were not destroyed and so there is FD refcount leak.
Calling `disconnect` that handles the stream too worked for me.
> Fix refcounted FD leak in HTTPClient

- README.md
The repository was migrated a while ago.
> Fix README link to point to travis-ci.com

- stream/vibe/stream/wrapper.d
Well it's a workaround for this particular issue.
Problem is that in `StreamOutputRange` destructor `flush()` is called to make sure that data has been written.
But when exception is thrown in it, destructor won't cleanup what'll normally be cleaned up and so the leak.
I've fixed it by resetting m_fill in a flush itself but it works only when written data are bigger than the internal buffer so flush is called and fails before the destructor.
For this case to work I've added manual `flush()` to `doWriteJsonBody()` so it's called before the destructor.
But there are much more places this can cause random problems and I'm not sure what would be the best approach for this. But throwing exceptions in destructors or allocating in them can easilly lead to `InvalidMemoryOperation` when called …
> Fix #2484 - clear  `m_fill` on flush exception

- http/vibe/http/fileserver.d
Changes the internal representation of a range to be end-exclusive (consistent with D slices) to avoid unsigned integer wrap-around for zero sized files.
See https://github.com/vibe-d/vibe.d/pull/2481#discussion_r504012709.
> Refactor Range header parsing into a separate function and fix handling of zero-sized files

- examples/http_info/views/info.dt
- examples/http_request/source/app.d
- examples/http_request_digest/source/app.d
- http/vibe/http/client.d
- inet/vibe/inet/webform.d
- utils/vibe/utils/dictionarylist.d
- utils/vibe/utils/string.d
The `alias this` deprecation in particular is quite painful.
> Remove some deprecated code

- data/vibe/data/json.d
- data/vibe/data/serialization.d
This change should reduce the number of memory allocations when using toString custom serialization
> Added sink type toString to the serialization

- .github/workflows/ci.yml
- tests/tls/source/app.d
This will be a bit problematic for Buildkite.
@s-ludwig : See https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing and the result: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
This only does Ubuntu, as currently we can't merge any PR because a "Required" check (Travis) is not working anymore.
In the future I will try to add Mac.
> Replace travis-ci with Github Actions

- http/vibe/http/client.d
The 'Second attempt to send HTTP request failed' should be removed
so the persisntent and not-persistent http requests are handled
the same way. Full discussion is on the issue page
fixes: #2451
> Fixing inconsistent error handling in http request

- data/vibe/data/serialization.d
Let IFTI do its thing, as it needs to for 'auto ref'.
> Sink serialization: Do not provide the type explicitly

- web/vibe/web/common.d
- web/vibe/web/rest.d
Added @ResultSerializer UDA to control serialization
> Implemented support for custom serialization

- data/vibe/data/json.d
- data/vibe/data/serialization.d
- stream/vibe/stream/wrapper.d
- web/vibe/web/common.d
- web/vibe/web/rest.d
This follows up on #2492 and #2493 and addresses the remaining issues. @ferencdg, please comment on any issues you might see, I could have broken a use case that I didn't see here.
> Serialization rework

- data/vibe/data/serialization.d
- web/vibe/web/common.d
- web/vibe/web/rest.d
This can save brandwidth and decrease latency of REST queries
usage:
```D
@serPolicy!(Base64ArraySerPolicy)
interface ITestBase64
{
@safe X getTest();
}
```
> Optionally serializing ubyte[] as base64 string

- mongodb/vibe/db/mongo/connection.d
```
Those deprecations are erroneous (it's a compiler bug),
as we only use the type which is not deprecated,
but the function with the same name is leads to a deprecation.
```
I didn't have time to track down the compiler bug yet, but this solves the issue in the meantime.
> Silence deprecations related to importing a deprecated symbol

- http/vibe/http/server.d
This change will help to mitigate simple DOS attacks
> Adding support for banning, un-banning TCP clients.

- web/vibe/web/rest.d
This addresses https://github.com/vibe-d/vibe.d/issues/2118
Documentation for vibe.web.rest was enhanced by:
* Being explicit about how function parameters are populated, and that in special cases they may affect the route path
* Reorder GET/PUT before POST/PATCH
* **Explicitly call out `id` as a magic function/method parameter name** that affects the route (not documented elsewhere)
* Describe the DMD bug #14369 (Vibe.d: #1043) as a CTFE problem
> docs: function parameter documentation including `id`

- web/vibe/web/rest.d
If the return value of the functioin is const,
trying to re-assiign 'ret' will throw an error inside vibe.d.
Since the only purpose of this separation was for a deprecation message
inside a __traits(compiles), we just use RT.init to give it the correct type,
and merge the two lambdas together.
> REST: Do not attempt to modify the return value

- tests/rest/source/app.d
- web/vibe/web/common.d
- web/vibe/web/internal/rest/common.d
- web/vibe/web/rest.d
Something I've been wanting for a while, should make user code much more friendly.
The names have changed to avoid weird overrides with the `headerParam` & co functions, but also to make function prototypes shorter.
> REST: Implement `viaBody`, `viaQuery`, `viaHeader` as parameters UDAs

- http/vibe/http/client.d
writefln could GC allocate, while printf is guaranteed not to.
> Do not use writefln in dtor

- tests/vibe.web.rest.2521/dub.json
- tests/vibe.web.rest.2521/source/app.d
- web/vibe/web/rest.d
```
While the server SHOULD provide Content-Type if it returns data,
it will most likely not if it doesn't return anything.
In this case, we treat it as application/octet-stream,
as prescribed by RFC 2616, section 7.2.1.
```
~Still testing locally, don't merge yet.~ Works
> Fix #2521: Do not require Content-Type for void return type

- examples/web-auth/views/home.dt
Assuming buildkite checks the example folders alphabetically, this should be the last one?
> Fix "web-auth" example for `Nullable` `alias get this` removal.

- redis/vibe/db/redis/types.d
Sorry for the spam! Instead of going back and forth between the Phobos PR's buildkite and this repo, this time I just ran all the `dub test` lines listed in `travis-ci.sh`. As far as I can tell, this is the last fix.
> Fix: remove implicit `Nullable` `.get` in redis/types.d pending Phobos removal.

- appveyor.yml
- data/vibe/data/json.d
Fix Issue 2205? The crashes haven't happened since.
> vibe.data.json: switch back to union for possible Json values

- http/vibe/http/client.d
`m_keepAliveLimit` must be compared to the current time.
`connected_time` is an `out` parameter that shouldn't be read before being initialized.
This bug was introduced in https://github.com/vibe-d/vibe.d/commit/560290a6bfc26a20e824a0c4808e32c4911b3f6c.
> Respect keep-alive on client requests

- web/vibe/web/common.d
Using 'in ref' is illegal when using -preview=in.
> web.common: Change 'in ref' to 'const scope ref'

- http/vibe/http/server.d
- tls/vibe/stream/openssl.d
Due to issue 9423, storage classes such as 'ref', 'in', and 'out'
are not inferred on delegate literals.
'scope' wasn't infered either, but due to the changes for DIP1000
ends up sometimes being infered.
> Work around 9423 by explicitly providing 'in' on delegates

- textfilter/vibe/textfilter/html.d
- textfilter/vibe/textfilter/markdown.d
- textfilter/vibe/textfilter/urlencode.d
Output ranges can be as simple as accepting a single element or a range of an element. Calling std.range.put instead of using the range's put member directly enables proper output range support.
> Fixes #2541 - use std.range.put properly for output ranges.

- web/vibe/web/common.d
- web/vibe/web/rest.d
Was recording `{"message: ""}` instead of an actual message.
> Fix handling of error status messages for RestException

- examples/file_operations/dub.json
- examples/file_operations/source/app.d
Debugging showed that the FileStream is destructed as soon as main is
exited (the task are running later). Interestingly, the bool can be
captured in the closure, but this seems not to work with the refcounted
FileStream. Passing the FileStream explicitely to the task as argument
solves that.
Unfortunately this is counter intuitive, as both bool and FileStream are
value types and we need to handle one differently from the other.
Fixes #2547
p.s. i also ran the app.d through dfmt (with defaults). If thats a problem
I am happy to do another patch without the formatting.
> Fix file example

- http/vibe/http/websockets.d
It's part of the public API of IncomingWebSocketMessage and should be available as well.
https://vibed.org/api/vibe.http.websockets/IncomingWebSocketMessage
> Websockets: make FrameOpcode public

- http/vibe/http/fileserver.d
- http/vibe/http/server.d
Also fixes a bogus secondary exception caused by attempting to parse ulong.max as long.
> Fix HTTP content.length header for content-ranges responses.

- .github/workflows/ci.yml
Change 'every 5 releases' to 'last 4 releases then every 5 releases',
as it is most likely that users are stuck one or two version back.
Currently assumes that ldc-latest is v1.27.0, which is yet to be released,
but should be soon.
> CI: Update supported compiler

- data/vibe/data/bson.d
- data/vibe/data/json.d
- data/vibe/data/serialization.d
An attempt to fix #1647
~~Still WIP, because of:~~
> Don't throw on unknown JSON input fields

- mongodb/vibe/db/mongo/collection.d
Iterating over Bson is explicitly defined as `@system`, but `@safe` capability is there
> make MongoCollection aggregate `@safe`

- http/vibe/http/router.d
- http/vibe/http/server.d
Uses MD5 as a sufficiently collision robust replacement for the simple 32/64-bit hash used before.
Fixes #2561
> Fix frequent hash collisions when disambiguating router match graph

- tests/rest/source/app.d
- web/vibe/web/internal/rest/common.d
- web/vibe/web/rest.d
This also allows `in` parameters to be used with
`--preview=in`.
> Allow `const` parameters in REST generator

- meson.build
Fixes error of using vibe.d as subproject:
subprojects/vibe.d-0.9.3/meson.build:37:4: ERROR: Function 'add_global_arguments' cannot be used in subprojects because there is no way to make that reliable.
Please only call this if is_subproject() returns false. Alternatively, define a variable that
contains your language-specific arguments and add it to the appropriate *_args kwarg in each target.
> Meson: fixes using vibe.d as subproject

- web/vibe/web/i18n.d
Accepting "en" should match "en_US", not just as a fallback, like it's the case with accepting "en_GB" and providing "en_US" instead.
This required fixing two existing bad test cases.
> Fix language matching for basic language specifiers.

- tests/rest/source/app.d
- web/vibe/web/rest.d
Allows to process large response bodies without loading everything into RAM.
> Add support for InputStreamProxy REST return type

- http/vibe/http/client.d
- http/vibe/http/common.d
- http/vibe/http/fileserver.d
- http/vibe/http/server.d
- http/vibe/http/status.d
- web/vibe/web/common.d
Note that the deprecated enum members in vibe.data.bson/json cannot realistically be marked as such, as that triggers thousands of deprecation warnings in Phobos when `to!T` is used together with `Json.Type` or `Bson.Type`.
> Use `deprecated` to deprecate enum members in :http

- http/vibe/http/server.d
This patch improves performance ~~about 5~8%~~ slighty.
Full bench log and bench.sh is [here](https://gist.github.com/kubo39/5a6786cb22d81f496ab4a1f7846e689c).
```console
+ git rev-parse HEAD
da8d30598bdf9401d512a46a077c62b061926e18
(...)
~/dev/dlang/vibe.d/examples/bench-http-server ~/dev/dlang/vibe.d ~/dev/dlang
+ wrk -c 1000 -d 10s http://localhost:8080/
Running 10s test @ http://localhost:8080/
2 threads and 1000 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    27.89ms   71.86ms   1.26s    97.89%
Req/Sec    25.07k     2.12k   31.55k    89.90%
498926 requests in 10.10s, 401.59MB read
Requests/sec:  49418.30
Transfer/sec:     39.78MB
+ wrk -c 1000 -d 10s http://localhost:8080/empty
Running 10s test @ http://localhost:8080/empty
2 threads and 1000 connections …
```
> Implement cache mechanism for GMT date strings.

- http/vibe/http/auth/digest_auth.d
This fixes https://github.com/vibe-d/vibe.d/issues/2597.
It has been broken after https://github.com/vibe-d/vibe.d/commit/0046c48bd8d85fe68fd07b1fa94ddabaf57e2f13 was committed.
This also fixes the expiration logic bug.
> Fix secret length mismatch at digest auth

- http/vibe/http/auth/digest_auth.d
This commit changes digest auth timeout interval: 5 minutes.
> 300 hecto-nanoseconds is too strict

- .github/workflows/ci.yml
- README.md
- appveyor.yml
If this works on the first try I'm going to buy a lotto ticket.
Main motivation, aside from the recent release of LDC v1.28.0, is to allow using `map` with `private` function, something not possible with v2.086 based frontend as there's a nasty visibility bug.
> Bump supported compiler version to v2.098.0 and dub to the modern age

- README.md
Ruby Homebrew installer is now deprecated.
> Update Homebrew install insturction

- inet/vibe/inet/url.d
Separates default port from `URL` and ties default port to common internet schema. Default behavior of `URL.defaultPort` is kept (returns 0 for unknown schemas). Built-in schemas are registered at init. 
**Changes**
- `StringSet` renamed and converted to `ushort[string]` map
- Built-in schemas are registered as common internet schemas
- New function implemented for getting default port of a registered common internet schema
**Decision points before merge**
- ✅ `registerCommonInternetSchema` can throw exception when schema is already registered within built-in schemas (or user schemas, user schemas can be updated silently) -> Schemas will be updated silently
- ~✅ `getDefaultPortOfCommonInternetSchema` can be `nothrow` (thus `@nogc`) and return 0 directly~
> Register default port for common internet schema

- inet/vibe/inet/url.d
Depends on #2626 due to an unittest, dependency can be removed easily.
URL normalization without semantic changes capability is added
- `normalize` method is added
- `normalized` method is added
> Normalization capability for URL

- inet/vibe/inet/url.d
Fixes #2618 and Fixes #492
Now plain `http://hello-🌍.com/🖐` input is valid for `URL`
Note: Variable names are chosen to match with pseudo-codes in [RFC3492](https://datatracker.ietf.org/doc/html/rfc3492)
- Ctor for `string` input of `URL` is extended with boolean parameter which specifies if `string` is already an encoded input (default)
- `parsePlain` static method is added to parse plain inputs
- Path, query and achor is percent encoded for plain inputs
- Subdomains and domain are puny encoded for plain inputs
> Percent encoding and Punycode support for plain URLs

- crypto/vibe/crypto/cryptorand.d
This pull request depends on https://github.com/dlang/dmd/pull/13169, trying to catch an out of bounds slice at compile time. Currently this would result in a compilation error at line 562, but given the fact that both digestLength!Hash and bufferSize are known at compile time, by replacing if with static if the program will work as expected.
> Update cryptorand.d - add a compile-time check

- web/vibe/web/rest.d
Those two types were undocumented, although they might be quite useful
for those wanting to customize error handling.
> vibe.web.rest: Add documentation for top-level types

- .github/workflows/musl.yml
- run-ci.sh
This is currently a copy of what's done in vibe-core, however vibe.d tests are a bit more complex and the basic `dub test` is not that useful.
> Add a workkflow to test Musl compatibility

- http/vibe/http/client.d
Fairly simple, de-duplicate the work done in multiple methods and allow other callers to do so, e.g. if one wants to have persistent connections in `vibe.web.rest`.
> http.client: Introduce an overload of connectHTTP that accepts URL

- stream/vibe/stream/counting.d
Fixes https://github.com/vibe-d/vibe.d/issues/2575.
> Fixes #2575: properly handle LimitedInputStream read IOMode

- inet/vibe/inet/url.d
Port check was missing. We can take default port into account for this, but since we have an URL normalizer, we can leave it to the user.
So, with this check; without normalization
`http://example.com/` and `http://example.com:80` will not be equal
> URL: Account for port in opEquals

- http/vibe/http/client.d
`defaultSettings` does not throw.
> Add nothrow to vibe.http.client.defaultSettings

- stream/vibe/stream/taskpipe.d
- tests/tls/dub.json
- tests/tls/source/app.d
- tls/vibe/stream/openssl.d
- tls/vibe/stream/tls.d
Updates the default cypher suite, removes dysfunctional SSLv3 support and adds a set of tests to check proper TLS version matching between client and server.
> OpenSSL TLS version handling improvements

- tls/vibe/stream/openssl.d
> Fix OpenSSL version check for 3.x.x

- inet/vibe/inet/url.d
Avoids calling isCommonInternetSchema and instead derives this information from the URL itself. This is possible, because URLs that don't conform to the schema are not allowed to start with "//". See RFC 3986 section 3.3.
> Fix using URL("...") at compile time.

- http/vibe/http/server.d
- tests/vibe.http.server.reject-predicate/dub.sdl
- tests/vibe.http.server.reject-predicate/source/app.d
TCP connection client address was not enough for configurations behind
reverse proxies. This will allow rejecting connections from actual
clients behind proxies.
Fixes #2639
> Invoke reject connection predicate with `X-Forwarded-For`

- .github/workflows/ci.yml
- .gitignore
- appveyor.yml
- tls/dub.sdl
- tls/vibe/stream/openssl.d
```
For a long time, the tls subpackage was stuck on OpenSSL bindings v1.x.x.
Those haven't been released for a long time, and the binding's version
did not match OpenSSL. Over time, workarounds were built to support
multiple versions of OpenSSL, but the issue applied to any OpenSSL user,
and the pin to the v1 major version means that a user could not use
the v2 branch and Vibe.d in the same application.
The main improvement that was done downstream was to auto-detect
the OpenSSL version. The script has now been ported to the binding package,
which can now be used by all downstream applications.
The position on multiple version has now been clarified,
and it has been decided that the bindings will now support a range of versions,
with static if / version condition when necessary.
In order …
```
> Update Deimos OpenSSL bindings to v3.0.0

- inet/vibe/inet/urltransfer.d
Using the `download` function from `vibe.inet.urltransfer` would throw a deprecation message because of `HTTPStatus.OK`.
> Fix download deprecation

- tls/vibe/stream/openssl.d
This partially reverts commit f8b62dc13877b988e2421c5a4be7893e1e2d9657,
as the WebSocket tests currently fail on Buildkite (OpenSSL 1.0.2).
> Partially revert dropping redundant OpenSSL declarations

- .github/workflows/musl.yml
- CHANGELOG.md
- meson.build
The dflags are gone as they are now done exclusively in OpenSSL
> Update changelog/meson file for v0.9.5

- textfilter/vibe/textfilter/markdown.d
See https://github.github.com/gfm/#tables-extension-
> Allow spaces around Markdown table header separators.

- .github/workflows/ci.yml
- .github/workflows/mongo.yml
- data/vibe/data/bson.d
- mongodb/vibe/db/mongo/collection.d
- mongodb/vibe/db/mongo/connection.d
- mongodb/vibe/db/mongo/cursor.d
- mongodb/vibe/db/mongo/database.d
- mongodb/vibe/db/mongo/flags.d
- mongodb/vibe/db/mongo/impl/crud.d
- mongodb/vibe/db/mongo/impl/index.d
- mongodb/vibe/db/mongo/sessionstore.d
- mongodb/vibe/db/mongo/settings.d
- tests/mongodb/_connection/dub.json
- tests/mongodb/_connection/source/app.d
So there was a bunch of legacy code from ancient MongoDB driver versions still around, which made this a bit difficult. I mostly kept old compatibility in, however since this release we are only going to officially support MongoDB 3.6 and up. (which has long been EOLd anyway) In theory a bunch of stuff still works with even older servers though, but I would not give any guarantees there. Methods that I could not upgrade transparently I simply deprecated with a note that they will stop working on MongoDB 5.1 and up, due to them dropping support for all packets except OP_MSG, which is now used everywhere.
The basic find method without and with query was upgraded transparently, however you can no longer use $query and query fields inside your query to overwrite the whole query. (was never …
> MongoDB 5.1+ driver compatibility

- data/vibe/data/bson.d
- data/vibe/data/serialization.d
- examples/bench-mongodb/source/app.d
- examples/mongodb/source/app.d
- mongodb/vibe/db/mongo/collection.d
- mongodb/vibe/db/mongo/connection.d
- mongodb/vibe/db/mongo/database.d
- mongodb/vibe/db/mongo/sessionstore.d
- tests/mongodb/index/source/app.d
- tests/mongodb/insert-remove-aggregate/source/app.d
Also tests it + fixed examples + fixed deprecations
Restores backwards compatibility with older code using returnFieldMapping. I noticed the old remove/update functions are always gonna still use the old behavior. We could in theory add compatibility layers there to let users just use the old API, but I would prefer users to upgrade to the better standardized API that's common across all drivers.
> reimplement MongoCollection.find with projection

- inet/vibe/inet/url.d
So far it didn't have an effect and the documented behavior was not implemented at all.
> Add a simple implementation of the existing parseUserURL "default_schema" parameter.

- stream/vibe/stream/wrapper.d
Deprecation showed up when I did `dub test`.
> Change an instance of 'in' to 'scope const'

- .github/workflows/ci.yml
- examples/bench-http-request/source/app.d
- examples/bench-http-server/source/app.d
- examples/read_write_mutex/source/app.d
- examples/redis-pubsub/source/app.d
- examples/rest-collections/source/app.d
- examples/task_control/source/app.d
- examples/uploader/source/app.d
- run-ci.sh
- tests/std.concurrency/source/app.d
Now that vibe-core 2.0.0 is tagged, it will be chosen by default, so we need to force testing 1.x.x.
This revealed a few issues in the build matrix and some additional compile errors in the example projects that need to be fixed.
> Reverse the vibe-core 1.x.x/2.x.x test configurations.

- mongodb/vibe/db/mongo/cursor.d
- tests/mongodb/cursor/dub.json
- tests/mongodb/cursor/source/app.d
Fixes a regression introduced by the revamped MongoDB driver.
> Fix duplicate database name in namespace for MongoDB cursor getMore calls

- tls/dub.sdl
- tls/vibe/stream/botan.d
- tls/vibe/stream/openssl.d
Fixes a bogus dependency to the openssl dynamic libraries after the latest package recipe refactoring w.r.t. the new static configuration. By setting "VibeNoSSL", this also strips TLS code in the HTTP server.
> Force all TLS related code to be stripped for the notls configuration

- stream/vibe/stream/bufferedstream.d
Modifying the peek buffer without setting the "dirty" flag of the respective buffer caused changes not to be committed to the underlying stream. This needs a more complicated approach in order to stay as efficient, so for now this just reverts to the previous behavior.
> Fix BufferedStream.write

- data/vibe/data/bson.d
immutable is not required because the `value` characters are copied into the internal buffer.
> Relax requirement of string value to const(char)[] value

- mongodb/vibe/db/mongo/collection.d
- tests/mongodb/_connection/source/app.d
I'm not sure about this fix since I'm not at all a mongo expert, but this does seem in line with the documentation for what update commands should look like.  Figured this was a good starting point.
> mongo updateimpl: check update, not field for updates

- data/vibe/data/json.d
- utils/vibe/internal/conv.d
Avoids using formattedWrite directly in order to avoid warnings when passing a scope output range.
Also marks the `line` parameter of `parseJson` `scope` (which probably isn't inferred as such due to the recursive nature of `parseJson`).
See also #2724.
> Fix scope related deprecation warnings in vibe.data.json

- stream/vibe/stream/cached.d
Allows to convert an input stream into a random access stream by caching its contents in a file.
> Implement CachedFileStream

- stream/vibe/stream/cached.d
Moves all members into the `CTX` struct that needs to be maintained anyway. This reduces the instance size in order to ensure it fits into an interface proxy. All associated resources are now freed upon calling close().
> Reduce the size of CachedFileStream and destroy underlying streams on close()

- stream/vibe/stream/semaphore.d
Allows limiting the number of concurrent I/O operations of an existing set of streams.
> Implement SemaphoreStream.

- http/vibe/http/server.d
Instead of using a hard-coded length of 4096 for the maximum size of lines in the HTTP headers (including the status line), make this configurable in HTTPServerSettings.
> Add server setting for max HTTP request header line length.

- http/vibe/http/server.d
RFC822 date/time strings can be larger than 29 characters if an unnamed time zone is used. Extending the buffer to 32 leaves one byte of slack for the longest possible string: "Wed, 02 Oct 2002 08:00:00 +0200"
> Avoid possible array bounds error.

- tests/rest/source/app.d
- web/vibe/web/rest.d
Instead of by name, enum values were serialized by value, causing a conversion error on the server side. This now mirrors the cases in `fromRestString` to `toRestString`, ensuring they match up.
> Fix handling of enum parameters for REST interface clients

- mongodb/vibe/db/mongo/collection.d
was probably accidental that we allowed UpdateOptions in there
Now we just allow both since the structs are almost equivalent
> add mongodb.replaceOne overload taking ReplaceOptions

- mongodb/vibe/db/mongo/collection.d
- mongodb/vibe/db/mongo/connection.d
- mongodb/vibe/db/mongo/impl/crud.d
- tests/mongodb/insert-remove-aggregate/source/app.d
e.g. index constraints failing wasn't throwing any exceptions anymore - now throws a sub-class of MongoException (not MongoDBException)
> fix MongoDB CRUD not throwing on error

- data/vibe/data/serialization.d
- mongodb/vibe/db/mongo/collection.d
- mongodb/vibe/db/mongo/connection.d
Since the original PR unfortunately got stuck, this is using and extending the unit tests by @madmax-inc in #2345 and replicates the manual value-to-enum conversion with an added `NoDuplicates` to fix handling of enums with duplicate values.
Fixes #2209. Closes #2345.
> Fix deserialization of string based enum types

- examples/rest-collections/source/api.d
- examples/rest-collections/source/app.d
- examples/rest-js/source/app.d
- tests/restclient/source/app.d
- tests/restcollections/source/app.d
- tests/vibe.web.rest.1125/source/app.d
- tests/vibe.web.rest.1140/source/app.d
- tests/vibe.web.rest.1230/source/app.d
- tests/vibe.web.rest.1922/source/app.d
- tests/vibe.web.rest.2506/source/app.d
- tests/vibe.web.rest.auth/source/app.d
- web/vibe/web/rest.d
Takes up on #2748 and uses a clear error message instead of letting the compiler output indirect errors.
Closes #2748.
> Remove support for non-safe REST methods

- mongodb/vibe/db/mongo/connection.d
- mongodb/vibe/db/mongo/cursor.d
unsure how this hasn't triggered before - checked and fixed on MongoDB 7 now
> MongoDB: fix cursor destructors

- .github/workflows/ci.yml
- run-ci.sh
- tests/vibe.http.client.1389/source/app.d
- tests/vibe.http.client.1426/source/app.d
- tests/vibe.http.server.listenHTTP/source/app.d
The CI jobs on Windows have been a no-op ever since they were introduced to replace the ones traditionally run through AppVeyor. This fixes the CI recipe to use bash, which now actually causes the tests to run.
> Revive Windows CI

- http/vibe/http/client.d
- http/vibe/http/common.d
- http/vibe/http/server.d
- inet/vibe/inet/message.d
- stream/vibe/stream/memory.d
- stream/vibe/stream/operations.d
- utils/vibe/utils/array.d
- utils/vibe/utils/string.d
Generalizes the code to take either IAllocator or RCIAllocator.
> Make the code forward compatible with std.experimental.allocator

- dub.sdl
Currently results in warnings during the build.
> Remove workaround for ancient DUB versions and old vibe.d directory structure

- mongodb/vibe/db/mongo/cursor.d
This adds a check to the destructor to avoid running into an InvalidMemoryOperationError and instead outputs a more descriptive error message without crashing. This also swaps back the order of operations in killCursors() so that no connection to the server gets allocated by the call if the cursor has already been killed.
Fixes #2793.
> Avoid possible GC allocations in MongoCursor.~this

- web/vibe/web/auth.d
- web/vibe/web/internal/rest/common.d
- web/vibe/web/rest.d
- web/vibe/web/rpc.d
This implements a bi-directional alternative to the REST interface system, enabling HTTP based peer-to-peer communication over a unidirectional HTTP/TCP connection.
> Implement a bi-directional WebSocket based RPC system

- examples/bench-mongodb/source/app.d
- mongodb/vibe/db/mongo/collection.d
Avoids accidental misuse of the API, erroneously treating the FindOptions value as the query.
> Add a MongoCollection.find(FindOptions) overload.

- tests/rest/source/app.d
- web/vibe/web/common.d
- web/vibe/web/internal/rest/common.d
- web/vibe/web/rest.d
Allows customizing the HTTP response status in a cleaner way than (ab)using an `@after` annotation.
See https://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/279951/
> Add viaStatus REST interface attribute.

- CHANGELOG.md
- redis/vibe/db/redis/idioms.d
- redis/vibe/db/redis/types.d
Note that this is a potentially breaking change in the case of the opApply adjustments.
> Make the Redis high-level APIs safe.

- CHANGELOG.md
- web/vibe/web/web.d
Since `Nullable!T` has removed the `alias this`, static members cannot be accessed via the `Nullable` anymore.
> Fix compilation error for Confirm!T parameters

- mail/vibe/mail/smtp.d
As the connection is more likely to hand on read than connect.
> feat(smtp/sendMail): Also use timeout as readTimeout
