- source/vibe/inet/message.d
> use parseRFC822DateTime from std.datetime

- README.md
This has been discussed in various place, but there's no official doc that state it ATM.
> Add official supported compiler / version in the README

- .travis.yml
Test all the drivers on all supported compiler.
The downside of this is that it requires 18 jobs: https://travis-ci.org/Geod24/vibe.d
It would however need a dub improvement: https://github.com/D-Programming-Language/dub/issues/520
> [WIP] Test libevent, libev and libasync drivers

- .gitignore
- .travis.yml
- dub.json
- source/vibe/core/drivers/libev.d
- source/vibe/core/net.d
Depends on https://github.com/D-Programming-Deimos/libev/pull/10 (and you making a new tag ;) ).
> Fix libev build

- source/vibe/db/redis/redis.d
As written on http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/24144/
> Implement zrangeByLex 

- .travis.yml
> Fix syntax on travis

- source/vibe/internal/meta/codegen.d
- Fixed ParameterTuple to have a saner API and take default parameters of different types, and even functions! But you won't be able to access it :-(
- Added CloneFunctionDecl, which clones a declaration (think CloneFunction without body).
- Added ability to CloneFunction to clone UDAs as well.
> Vibe.internal.meta.codegen fixes

- source/vibe/internal/meta/codegen.d
- source/vibe/web/rest.d
> Workaround #1045 / 14375

- source/vibe/core/args.d
- source/vibe/core/core.d
- source/vibe/core/log.d
- source/vibe/data/bson.d
- source/vibe/db/redis/redis.d
- source/vibe/http/client.d
- source/vibe/http/common.d
- source/vibe/http/log.d
- source/vibe/http/server.d
- source/vibe/templ/diet.d
- source/vibe/utils/hashmap.d
- source/vibe/web/rest.d
- source/vibe/web/validation.d
Newest DMD is more picky about implicit conversion of arrays to bool, see this PR:
https://github.com/D-Programming-Language/dmd/pull/2885
> Use explicit checks for arrays in boolean contexts

- source/vibe/web/rest.d
http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/25414/
> REST: Provide a better error message when user has no / multiple interfaces

- source/vibe/web/rest.d
Basically non-controversial part of #1091 - I'd like it not to bitrot.
I'm probably going back on #1091 later this week, and add the `Nullable` support you wanted.
> [REST] Cleanup / refactoring

- source/vibe/core/drivers/libasync.d
The connectTCP function was returning correctly even though the connection attempt had failed.
> Fix infinite connection attempt

- source/vibe/core/drivers/libasync.d
This fix will display DNS resolver errors rather than a single default exception message..
> Show DNS resolver exception messages

- source/vibe/web/i18n.d
Example: `mixin translationModule!"path/to/po/file";`
> Allow paths with '/' in translationModule

- source/vibe/db/redis/redis.d
I've stumbled across this bug and just wrote a pull request real quick.
> fix redis config command order

- .travis.yml
> Allow other driver to build / run more easily

- dub.json
- source/vibe/appmain.d
- source/vibe/core/core.d
- source/vibe/core/drivers/libasync.d
- source/vibe/core/log.d
- source/vibe/http/client.d
- tests/restclient/dub.json
This is for 2.068.0 but also fixes a GC error that prevents it from going green
> http/2 botan - Try going green

- .travis.yml
Commit 5ad972e567b2ef9254a69de3562ef057d5d03364 incorrectly set it so that we were testing everything.
> Fixup for rejectedsoftware/vibe.d#1161: Allow other driver to test

- source/vibe/vibe.d
> Add digest_auth to the single module file vibe.d

- dub.json
- source/vibe/appmain.d
- source/vibe/core/core.d
- source/vibe/core/drivers/libasync.d
- source/vibe/core/log.d
I had already seen this coming, in my great master plan
ping @Geod24  ;)
> Libasync fix 2.068.0 b1

- source/vibe/inet/webform.d
Fixes #1167
Also adds a unittest for #1167
> Correctly parse quoted boundary field for multi part form

- source/vibe/core/connectionpool.d
- source/vibe/core/sync.d
These were now tested in a [postgresql driver](https://github.com/etcimon/ddb/blob/master/source/ddb/postgres.d#L2243).
> Fix ConnectionPool and LocalTaskSemaphore

- source/vibe/web/rest.d
> added docs for DELETE mappings

- source/vibe/core/drivers/win32.d
Fix for same problem as #1098 but on win32 driver.
And additionally resolve method name conflict with 2.068
> Fix win32 with 2.068

- source/vibe/http/internal/http2.d
HTTP2Stream read method was aborting before the end causing errors on large reads.
> Stability fixes for HTTP/2

- .travis.yml
- README.md
> Drop support for frontend <= 2.065 and test with 2.068 release

- source/vibe/http/client.d
Make sure no connection header is in the client requests
> Connection header causes protocol error

- .travis.yml
- travis-ci.sh
- makes it easier to manually test vibe.d
- choose decent default values for env vars
> move test script to a separate file

- source/vibe/http/internal/http2.d
The data_processed flag was keeping the stream hanging, and uploads didn't send more than one data frame. Also, fixes access violation on empty header value.
> Fix http/2 hanging request streams and uploads

- source/vibe/http/cookiejar.d
Use a parse format for epoch comparison to avoid string mistakes that prevent sessions from being cleared
> Fix Cookie Expires

- source/vibe/core/core.d
This commit turns setupWorkerThreads into a public function and adds an
additional parameter to specify the number of worker threads to setup.
This parameter defaults to threadsPerCPU to keep the old behavior by
default.
> Pass number of worker threads to setupWorkerThreads

- tests/mongodb/source/app.d
- the new storage engine no longer has an admin database
- also print a proper exception message when a test fails
> fix test for MongoDB WiredTiger compat

- examples/rest/source/app.d
> Fixed typo.

- source/vibe/http/common.d
- source/vibe/http/server.d
> make parseCookies parse cookies as rawCookies

- source/vibe/core/drivers/libasync.d
The allocations were inconsistent with binary increments and were hard to debug. This fixes it.
> [Libasync] ManualEvent - Fix Race Condition and Optimize Space Usage

- source/vibe/core/log.d
- it might make sense to have newlines in a log message
(e.g. when printing a backtrace) and they shouldn't
be split into multiple log messages, e.g. when using syslog
- the splitting was poorly done anyhow (only on the first LF)
> don't split log lines on LF

- source/vibe/http/status.d
IETF RFC:
https://tools.ietf.org/html/draft-ietf-httpbis-legally-restricted-status-04
> Added HTTP 451 status code and message

- source/vibe/core/core.d
- source/vibe/utils/hashmap.d
> Fix compilation with master && remove usage of CommaExp

- source/vibe/http/websockets.d
@s-ludwig : After looking at the code in this module, I believe it needs serious work before being ready for production.
This P.R. will mitigate some of the issues I encountered, but things like https://github.com/rejectedsoftware/vibe.d/issues/1496 make it completely unusable for any serious application.
I tested this with a crippled version of my Slack bot, however I was blocked by https://github.com/rejectedsoftware/vibe.d/issues/1475 (as only an old frontend, such as GDC's, produce correct code, but Vibe.d's master is not compatible with 2.067 anymore). I'll try to invest some time in tracking the issues in the near future.
> Put some band-aid on WebSocket

- source/vibe/data/json.d
- source/vibe/utils/memory.d
Fixes https://github.com/rejectedsoftware/vibe.d/issues/1522
> DMD 2.072 fixes

- source/vibe/core/concurrency.d
At least it seems like it refers to the same thing.
Not sure how to do the linking correctly here.
> vibe.core.concurrency: Update references to Isolated template

- source/vibe/stream/botan.d
There was some breaking changes with v1.12.6.
SSL_V3 protocol version removed and new abstract method.
> Fix compilation with botan v1.12.6

- source/vibe/db/mongo/flags.d
Fixes current travis build problems
> Fix missing coma

- source/vibe/mail/smtp.d
> declare SMTPClientSettings parameter of sendMail as 'in'

- tests/restclient/source/app.d
- fixes tests with modified sorting function (https://github.com/dlang/phobos/pull/4816)
> sort allow methods before comparing

- http/vibe/http/client.d
> Properly set use_tls for unix sockets

- appveyor.yml
- core/vibe/core/path.d
- http/vibe/http/fileserver.d
- http/vibe/http/router.d
- http/vibe/http/server.d
- inet/vibe/inet/url.d
- inet/vibe/inet/webform.d
- web/vibe/web/rest.d
This makes the code base compatible with the latest vibe-core 1.0.0-beta.8, including forward compatibility definitions in vibe-d:core.
> Update for vibe-core path definition changes.

- meson.build
- remove leftover install_headers
- fix typo
> small fixup of #1720

- core/vibe/internal/allocator.d
- data/vibe/data/bson.d
- http/vibe/http/client.d
- http/vibe/http/server.d
- inet/vibe/inet/message.d
- stream/vibe/stream/memory.d
- stream/vibe/stream/openssl.d
- stream/vibe/stream/operations.d
- utils/vibe/internal/utilallocator.d
- utils/vibe/utils/array.d
- utils/vibe/utils/hashmap.d
> Fix the type extracted from InterfaceProxy

- scripts/tag_version.sh
- scripts/test_version.sh
- travis-ci.sh
- also add small helper script to update and tag a new version
> test that versions strings are equal

- stream/vibe/stream/operations.d
Btw there's trailing whitespace in your file...
> Fix typo in vibe.stream.operations.readAllUTF8

- data/vibe/data/serialization.d
This PR adds tuple deserialization support. It also includes few fixes for the places where using tuple was not supported.
> Fix #1691 - Add tuple deserialization support

- data/vibe/data/serialization.d
This whitespace managed to sneak in...
> Remove (sneaked in) trailing whitespace

- README.md
Inspired from https://github.com/dlang/dlang.org/pull/1763
I think providing a simple hello world is very important for newcomers.
Incidentally I observed quite recently a [discussion with a similar consensus on the NG](http://forum.dlang.org/post/oimi34$q4p$1@digitalmars.com) about this as well.
> Add Hello vibed example to README

- http/vibe/http/client.d
> Write content length header for HTTPClientRequest.writeFormBody

- textfilter/vibe/textfilter/markdown.d
> Filter URLs in Markdown documents by a whitelist of schemas

- core/vibe/core/core.d
This avoids "dwarfeh(224) fatal error" that happens when exit() is called while an Error in in flight.
> Use abort() for fatal exit and avoid catching Throwable unless really necessary.

- tls/vibe/stream/openssl.d
Storing and rethrowing exception can be problematic in some cases and precludes the use of non-GC exceptions down the line if the `@nogc` exception proposal gets implemented.
> Remove checkExceptions logic and rely on OpenSSL's error mechanism instead.

- tls/vibe/stream/openssl.d
Make build with OpenSSL 1.1 work again.
See #1892
> OpenSSL 1.1 fixes

- scripts/tag_version.sh
- scripts/test_version.sh
- travis-ci.sh
> Adjust version scripts for new meson version approach and re-enable CI

- http/vibe/http/websockets.d
> Add nothrow WebSocket handler overloads and deprecate the rest.

- data/vibe/data/json.d
There's still some other stuff that doesn't work at compile time for various reasons, but this at least takes care of the low hanging fruit.
> Fix an error parsing json at compile time.

- http/vibe/http/server.d
I know that `req.path` is about to be deprecated and will disappear with the upcoming rewrite of the http module. However, as `parseURL` is often set by default, we can save quite a bit _today_ without doing any hard work.
> Make HTTPServerResponse.path lazy

- redis/vibe/db/redis/redis.d
- tests/redis/source/app.d
>  Wait for stop in RedisSubscriberImpl.~this()

- .travis.yml
- travis-ci.sh
- replace ad-hoc BUILD_EXAMPLE & RUN_TEST mechanism
- allows to test components in parallel
> more control over running test components

- .travis.yml
- README.md
- appveyor.yml
- travis-ci.sh
As a side effect this should fix the Travis failures.
Lacking a Windows VM, I did the changes to `appveyor.yml` blindly.
> Bump versions to 2.078.0

- http/vibe/http/websockets.d
Required for https://github.com/dlang/dmd/pull/7241
> Fix import leak

- .codecov.yml
See also: https://github.com/dlang/dub/pull/1347
> Improve CodeCov setup - hide codecov/project

- crypto/vibe/crypto/cryptorand.d
Note: on the listed platforms `arc4random_buf` is not based on RC4 but on a modern and cryptographically secure cipher.
> On systems with secure arc4random_buf use it instead of /dev/urandom

- web/vibe/web/rest.d
Enables user code to provide a custom error handling callback for writing error replies with a custom format.
> Add RestInterfaceSettings.errorHandler.

- mongodb/vibe/db/mongo/connection.d
Applied the comment from
https://github.com/vibe-d/vibe.d/issues/1967#issuecomment-349782134
> Use old MongoAuthMechanism if explictly stated

- README.md
I will also have time on bringing more runnable examples on the DTour, but of course anyone having interested can help out too.
See e.g.
- https://tour.dlang.org/tour/en/dub/mir-algorithm
- https://github.com/wilzbach/vibe-d-by-example (WIP)
> Add link to quickstart with the example on run.dlang.io

- data/vibe/data/serialization.d
> Fix detection of single-element tuples in the serializer.

- crypto/vibe/crypto/cryptorand.d
> Bionic C runtime has secure arc4random

- source/vibe/stream/openssl.d
Includes #1651, #1748, #1758, #1759, #1921, #1981, #2117
> Backport OpenSSL fixed from master.

- source/vibe/http/router.d
> Backport fixes to URLRouter from master.

- mongodb/vibe/db/mongo/settings.d
std.digest.digest has been moved to std.digest.
> Fix the std.digest.digest deprecation message

- inet/vibe/inet/webform.d
Fix tests for [druntime#2243](https://github.com/dlang/druntime/pull/2243)
Order of AA elements is not determined.
> [trivial] fix aa tests

- tls/vibe/stream/openssl.d
The current implementation doesn't compile when ALPN is enabled (with openssl version >= 1.0.2 or `version=VibeForceALPN`) since `@safe` methods are not allowed to manipulate `extern(C)` pointers and ubyte arrays, causing compile-time errors.
The changes proposed wrap the affected statements in `@trusted` blocks so that the manipulation is allowed.
> trusted methods for openssl alpn

- .travis.yml
- README.md
- appveyor.yml
> Update compiler support to 2.076.1-2.080.0.

- .travis.yml
- issue 13742 was fixed with 2.078.1
> remove coverage workaround

- examples/websocket/public/scripts/websocket.js
It was hard to tell what was going on in the function
> simplify getBaseURL

- tests/dirwatcher/source/app.d
- tests/redis/source/app.d
- tests/restclient/source/app.d
- tests/tcpproxy/source/app.d
- tests/vibe.http.server.listenHTTP/source/app.d
Required for https://github.com/dlang/dmd/pull/9636
> Add private imports explicitly

- examples/rest-js/source/app.d
For https://github.com/dlang/dmd/pull/9636 to pass the buildkite test suite.
cc @wilzbach
> Add selective imports to rest-js example in support of upcoming DMD PR

- http/vibe/http/server.d
Alternative to https://github.com/vibe-d/vibe.d/pull/2298
Required s.t. options like https://github.com/vibe-d/vibe.d/pull/2297 can be set from the user.
> Allow to configure options of SessionVar

- inet/vibe/inet/url.d
- textfilter/vibe/textfilter/markdown.d
- utils/vibe/utils/string.d
This seems to be a relic from the time when indexOf was not CTFEable.
I can adjust the time of removal to your needs - I didn't knew if `v0.8.11` was a good idea :)
> Deprecate indexOfCT and use indexOf instead

- core/vibe/core/drivers/libevent2_tcp.d
- http/vibe/http/client.d
- http/vibe/http/common.d
- http/vibe/http/proxy.d
- http/vibe/http/server.d
- mail/vibe/mail/smtp.d
- mongodb/vibe/db/mongo/settings.d
- utils/vibe/utils/array.d
- utils/vibe/utils/dictionarylist.d
- web/vibe/web/common.d
- web/vibe/web/rest.d
- web/vibe/web/web.d
I was originally intending to clean up some `utils` code, and most importantly remove `sanitizeUTF8`, which `std.utf` can do quite well.
However I ended up finding a compiler bug and some unused fields, and found out that the approach I'd like to use wouldn't really work without a few bug fixes...
Best reviewed commit-by-commit. Each commit can be taken separately and compiled.
> Collection of code cleanup

- core/vibe/core/path.d
- inet/vibe/inet/url.d
> URL: pure ctors added

- web/vibe/web/rest.d
This does not add any value for the user
> Trivial: Remove leftover development logDebug

- http/vibe/http/common.d
> Simplified parseHTTPVersion

- .travis.yml
See https://github.com/dlang/installer/pull/301 for details
> Use latest version of dub for Travis

- http/vibe/http/websockets.d
See commit message for details.
> WebSocket.close: Silently ignore exceptions for close message

- .travis.yml
- scripts/core-dump.sh
- tests/vibe.http.client.1426/dub.sdl
- tests/vibe.http.client.1426/source/app.d
Also do not use VibeDefaultMain and simply use a main instead.
> Do not use deprecated function in http client test 1426

- http/vibe/http/server.d
Could we remove more deprecations?
> Remove some deprecated items scheduled in 0.9

- data/vibe/data/json.d
- data/vibe/data/serialization.d
I suspect you'll want some tweaks to the formatting, so just LMK what you want to see.
> add some nothrow to json

- data/vibe/data/bson.d
Adds conversion back and forth between SysTime and BsonDate
> feat(Bson): convert SysTime to BsonDate

- textfilter/vibe/textfilter/markdown.d
Also refactors the code to use figure specific line types to separate list and figure parsing early on.
> Fix parsing of figures when following an ulist.

- http/vibe/http/server.d
Instead of the raw protocol contents, this allows to receive only the logical body contents.
> Add a way to control the output mode for createTestHTTPServerResponse.

- .travis.yml
- CHANGELOG.md
- data/vibe/data/bson.d
- http/vibe/http/log.d
- http/vibe/http/websockets.d
- utils/vibe/utils/hashmap.d
- web/vibe/web/rest.d
Merge fixes made to the point release.
> Merge tag `v0.9.2` into `master`

- stream/vibe/stream/wrapper.d
> Avoid redundant throwing in StreamOutputRange's destructor.

- web/vibe/web/rest.d
Following comments on https://github.com/vibe-d/vibe.d/issues/2415#issuecomment-588079108
closes: #2415
> Allowing refs in REST interface

- http/vibe/http/client.d
- tests/vibe.web.rest.2506/dub.json
- tests/vibe.web.rest.2506/source/app.d
> HTTP request reusing TCP connection leads to wrong response being processed

- data/vibe/data/serialization.d
serialization doesn't compile with the following configuration:
type supports sink type AND
serializer doesn't supoprt sink type
> serialization compile error fix: sink type related

- examples/rest/source/app.d
See https://github.com/dlang/phobos/pull/7761
> Fix "rest" example for `Nullable` `alias get this` removal

- tests/rest/source/app.d
> Fix tests/rest for alias Nullable.get this removal

- http/vibe/http/client.d
- http/vibe/http/server.d
- web/vibe/web/common.d
- web/vibe/web/rest.d
> Use/handle explicit charset declaration for JSON in the HTTP/REST system

- tests/tls/source/app.d
This obviously behaves differently based on the OpenSSL version used. Only the server tunnel result is relevant here.
See #2501
> Change the client cert fail test to ignore the client-tunnel result

- utils/vibe/internal/meta/codegen.d
> Ensure that getSymbols unqualifies types.

- mongodb/vibe/db/mongo/database.d
- tests/mongodb/_connection/source/app.d
> Add MongoDatabase.runListCommand for commands that return a cursor

- http/vibe/http/proxy.d
- http/vibe/http/websockets.d
- redis/vibe/db/redis/redis.d
- stream/vibe/stream/stdio.d
Fixes deprecation warnings with deprecated non-nothrow tasks and handles exceptions properly.
> Avoid uncaught exceptions in tasks

- appveyor.yml
- stream/vibe/stream/bufferedstream.d
BufferedStream buffers a source stream chunk-wise (read+write) to enhance random access performance.
> Add BufferedStream

- http/vibe/http/client.d
Avoid confusing people attempting to debug Vibe.d.
> vibe.http.client: Clarify that HTTPClient.connect does not actually connect

- data/vibe/data/json.d
This triggers a deprecation in v2.097.0.
> data/json: Add missing static import

- examples/web-i18n/source/app.d
- examples/web-i18n/translations/example.de_DE.po
- examples/web-i18n/translations/example.en_US.po
See https://github.com/rejectedsoftware/diet-ng/pull/92
> Fix i18n example translations

- README.md
- tls/dub.sdl
- tls/vibe/stream/openssl.d
See each commit, those should be fairly straightforward.
> Remove OpenSSL 0.9 support, correct README about default OpenSSL

- tls/vibe/stream/openssl.d
change minimized version of #2582
> Set max protocol version

- inet/vibe/inet/url.d
Allows to work with custom or less common double-slash style URL schemas more conveniently.
> Add isCommonInternetSchema and registerCommonInternetSchema APIs

- tls/vibe/stream/openssl.d
> Fix bogus diagnostic message for unapplied SSL option

- web/vibe/web/rest.d
Was looking into adding more features to our beloved `rest` module, figured I could remove a few spider webs first.
> Various cleanups in `vibe.web.rest`

- http/vibe/http/client.d
This PR exposes tlsPeerName in HTTPClientSettings.
Currently, `requestHTTP` functions are not usable against servers that implements [SNI (Server Name Identification)](https://datatracker.ietf.org/doc/html/rfc3546#section-3.1) with client making requests using an IP address. The TLS peer name is not being passed to the `createTLSStream` which leads to `421 Misdirected Request`.
Here is the minimal code sample to show the difference
```
/+dub.sdl:
name "test"
dependency "vibe-d" repository="git+https://github.com/vitalka200/vibe.d.git" version="472ae9061b6fc423cb907815c0ca98b25a086717"
+/
import vibe.core.log;
import vibe.http.client;
void main()
{
setLogLevel(LogLevel.trace);
logInfo("================ Only Host header is set ================"); …
```
> Expose tlsPeerName in HTTPClientSettings

- tls/vibe/stream/openssl.d
As explained in the comment, a breaking change happened while fixing a bug.
> openssl: Work around deimos/openssl change in 2.0.2+1.1.1.h

- .github/workflows/openssl.yml
- tls/vibe/stream/openssl.d
~WIP, still missing the "fix" part.~
> openssl: Add a workflow for OpenSSL v1.0.x and fix support

- tls/vibe/stream/openssl.d
The most common issue with C bindings strikes again.
Deimos definition: https://github.com/D-Programming-Deimos/openssl/blob/v3.0.1/source/deimos/openssl/ssl.d#L1984
> openssl: Fixup long -> c_long bindings for SSL_CTX_set_options

- tls/vibe/stream/openssl.d
The check included all versions >= 1.0.1, which covers the last 10 years.
> openssl: All supported versions have ECDH

- tls/vibe/stream/openssl.d
Using OPENSSL_VERSION.startsWith is prone to error,
while using OPENSSL_VERSION_BEFORE and OPENSSL_VERSION_AT_LEAST
is neither ambiguous nor as brittle.
> openssl: Remove OPENSSL_VERSION, use Deimos' features

- tls/vibe/stream/openssl.d
As explained in the comments, the init code is no longer necessary.
> openssl: Remove init code for 1.1.0 and later

- .github/workflows/openssl.yml
- tls/dub.sdl
- tls/vibe/stream/openssl.d
Still testing, will make the final release once this passes.
> Update openssl requirement to v3.1.0 and drop redundant declarations

- .github/workflows/openssl.yml
The install_sw one doesn't seem to work properly.
> OpenSSL CI: Use plain install command

- .github/workflows/ci.yml
- .github/workflows/musl.yml
- .github/workflows/openssl.yml
https://github.com/actions/checkout/pull/689
> update actions/checkout in GitHub Actions to v3

- mongodb/vibe/db/mongo/collection.d
> add projection parameter to findOne as well

- mongodb/vibe/db/mongo/collection.d
- mongodb/vibe/db/mongo/cursor.d
was using wrong arguments in ctor and missing override in templated class
> fix legacy find and MongoCursor

- stream/vibe/stream/bufferedstream.d
Reduces the overhead for very small consecutive reads/writes. Those showed up considerably in the profiler for image decoding loads.
> BufferedStream optimization

- data/vibe/data/json.d
- http/vibe/http/auth/digest_auth.d
- http/vibe/http/common.d
- http/vibe/http/fileserver.d
- http/vibe/http/router.d
- http/vibe/http/server.d
- http/vibe/http/websockets.d
- utils/vibe/utils/dictionarylist.d
- web/vibe/web/internal/rest/common.d
This fixes a number of some scope warnings, silences some with `@trusted` and cleans up some code to minimize the amount of changes needed to get rid of the warnings.
> Work on scope warnings and code cleanup

- mongodb/vibe/db/mongo/connection.d
The batchSize parameter must be greater than zero.
> Fix getMore database error on MongoDB 4.4

- http/vibe/http/client.d
Avoids undefined behavior in case of thrown exceptions when the object has only been partially initialized. In a concrete case, there was an assertion failure due to a corrupted FreeListRef that was caused by attempting to destroy the HTTPClientResponse object in the scope!HTTPClientResponse() call.
> Make HTTPClientResponse.this nothrow

- .github/workflows/mongo.yml
- run-ci.sh
- tests/mongodb/_connection/run.sh
upgrades all the mongo server versions to the latest minor versions
> Add MongoDB 7.0 to tests

- mail/vibe/mail/smtp.d
A fairly simple implementation allowing to send emails to M365 / gmail.
> Mail: Implement SMTP XOAUTH2 authentication

- examples/unix_socket/dub.sdl
See also #2809 - although this change is not required to fix the issue.
> Use configurations to compile without TLS support

- .github/workflows/ci.yml
Test with only the latest 10 releases.
> ci: Upgrade supported compiler & dub version

- mail/vibe/mail/smtp.d
Otherwise a program may get stuck indefinitely.
> feat(smtp): Allow to specify a timeout in sendMail
